-- 17 September 2026 daily current-affairs desk.
-- Ten original, primary-source-verified briefs, including recoverable late material from 14-16 September.

insert into public.current_affairs_briefs (
  slug, published_on, title, summary, why_it_matters, background,
  source_title, source_url, source_publisher, source_published_on,
  prelims_takeaways, quick_check, visual_data, status, reviewed_at
) values
('2026-09-17-epfo-wage-ceiling', '2026-09-17',
 'Cabinet approves a higher EPFO wage ceiling',
 'The Union Cabinet approved raising the wage ceiling for mandatory Employees'' Provident Fund Organisation coverage from Rs 15,000 to Rs 25,000 per month. The Labour Ministry expects more than 51 lakh additional employees to come within mandatory coverage.',
 'This is a social-security and labour-formalisation update. Approval is not the same as completed implementation: the release says statutory and administrative steps still remain.',
 'EPFO administers the Employees'' Provident Fund, Employees'' Pension Scheme and Employees'' Deposit Linked Insurance Scheme. The wage ceiling concerns mandatory coverage under the stated framework, not an employee''s take-home salary.',
 'Cabinet approves enhancement of EPFO wage ceiling from Rs.15,000 to Rs.25,000 per month', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310812&lang=1&reg=3', 'Ministry of Labour and Employment / Press Information Bureau', '2026-09-16',
 '["The approved mandatory-coverage ceiling rises from Rs 15,000 to Rs 25,000 per month.","More than 51 lakh additional employees are expected to come under mandatory coverage.","EPFO administers EPF, EPS and EDLI.","Cabinet approval and statutory implementation are different stages."]'::jsonb,
 '[{"question":"Which three schemes are administered by EPFO?","answer":"EPF, Employees'' Pension Scheme (EPS), and Employees'' Deposit Linked Insurance Scheme (EDLI)."},{"question":"Has every implementation step already concluded?","answer":"No. The release says statutory and administrative steps remain."}]'::jsonb,
 '{"title":"EPFO coverage change","steps":["Cabinet approves a higher wage ceiling.","Statutory and administrative action follows.","More eligible employees enter mandatory coverage.","EPFO-linked social security expands."]}'::jsonb, 'published', now()),
('2026-09-17-rcmc-small-export-exemption', '2026-09-17',
 'Small export consignments get an RCMC exemption',
 'The Directorate General of Foreign Trade amended paragraph 2.57 of the Foreign Trade Policy, 2023 so an RCMC or Certificate of Registration is not required for eligible export consignments with Free-on-Board value up to Rs 3 lakh. The normal requirement continues above that limit where otherwise applicable.',
 'This is a trade-facilitation measure for MSMEs and first-time exporters. The threshold is based on FOB value and does not remove other applicable export-law or customs requirements.',
 'An RCMC is normally obtained from an Export Promotion Council or Commodity Board. The de minimis exemption lowers an entry compliance barrier for low-value postal, courier and similar consignments.',
 'Government Eases RCMC Requirement for Export Consignments up to ₹3 Lakh', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310798&lang=1&reg=3', 'Ministry of Commerce and Industry / Press Information Bureau', '2026-09-16',
 '["RCMC means Registration-cum-Membership Certificate.","The exemption applies to eligible consignments with FOB value up to Rs 3 lakh.","Above Rs 3 lakh, normal registration continues where applicable.","Export Promotion Councils and Commodity Boards are usual registering bodies."]'::jsonb,
 '[{"question":"What valuation basis does the exemption use?","answer":"Free-on-Board (FOB) value."},{"question":"Does it abolish RCMC requirements for every export?","answer":"No. It is limited to eligible consignments up to Rs 3 lakh."}]'::jsonb,
 '{"title":"Low-value export entry route","steps":["Exporter checks FOB value.","Eligible consignments up to Rs 3 lakh receive the exemption.","Other trade and customs conditions continue.","Larger consignments use the normal framework where required."]}'::jsonb, 'published', now()),
('2026-09-17-india-electric-mobility-index-2025', '2026-09-17',
 'NITI Aayog releases the second India Electric Mobility Index',
 'NITI Aayog released the second India Electric Mobility Index, a data-based framework for States and Union Territories to track electric-mobility progress and improve their policies. The release says 29 of 36 States and UTs have notified EV policies.',
 'The index is a policy-measurement tool, not a law or subsidy scheme. It connects transport decarbonisation, charging infrastructure, batteries and the Centre-State division in EV implementation.',
 'The release places the index alongside FAME, PM E-DRIVE, PM E-bus Sewa and PLI support for automobiles/components and Advanced Chemistry Cell batteries. It also mentions the Unified Bharat e-Charge app.',
 'NITI Aayog launches second edition of India Electric Mobility Index', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310804&lang=1&reg=3', 'NITI Aayog / Press Information Bureau', '2026-09-16',
 '["IEMI means India Electric Mobility Index.","It helps States and UTs assess electric-mobility progress.","The release reports notified EV policies in 29 of 36 States and UTs.","FAME, PM E-DRIVE and PM E-bus Sewa are distinct supports mentioned with the transition."]'::jsonb,
 '[{"question":"Is IEMI itself an EV subsidy scheme?","answer":"No. It is an index for measuring policy progress."},{"question":"Who chiefly uses it to compare progress?","answer":"States and Union Territories."}]'::jsonb,
 '{"title":"Electric-mobility policy loop","steps":["States notify EV policies.","IEMI measures ecosystem progress.","Evidence identifies charging and capability gaps.","Policies are refined using those findings."]}'::jsonb, 'published', now()),
('2026-09-17-trade-watch-quarterly-q1-fy27', '2026-09-17',
 'NITI Aayog issues Trade Watch Quarterly for Q1 FY27',
 'NITI Aayog released the ninth Trade Watch Quarterly, covering April-June 2026. It assesses global and domestic trade conditions and makes India''s metals and ores trade the thematic focus, including the implications of the EU Carbon Border Adjustment Mechanism.',
 'This is a primary policy publication for trade and the economy. It is an analytical quarterly report, not a trade agreement or tariff notification.',
 'The release reports India''s total merchandise and services trade at US$506.9 billion in Q1 FY27, with 15.5% year-on-year growth. It relates metal-sector competitiveness to critical minerals, logistics, clean energy, recycling and CBAM preparedness.',
 'NITI Aayog Launches Ninth Edition of Trade Watch Quarterly', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310941&lang=1&reg=3', 'NITI Aayog / Press Information Bureau', '2026-09-16',
 '["The ninth Trade Watch Quarterly covers Q1 FY27, April-June 2026.","Its thematic focus is India''s metals and ores trade.","The report discusses the EU Carbon Border Adjustment Mechanism (CBAM).","A quarterly report is distinct from a trade treaty or tariff notification."]'::jsonb,
 '[{"question":"What is the thematic focus of this edition?","answer":"India''s metals and ores trade."},{"question":"What does CBAM stand for?","answer":"Carbon Border Adjustment Mechanism."}]'::jsonb,
 '{"title":"Trade-competitiveness frame","steps":["Report tracks global and domestic trade.","Metals and ores form the lens.","CBAM and supply-chain pressures affect competitiveness.","Policy responses include logistics, energy and recycling."]}'::jsonb, 'published', now()),
('2026-09-17-net-zero-portal-napcc-dashboard', '2026-09-17',
 'India launches the Net Zero Portal and NAPCC Dashboard',
 'The Environment Ministry launched a Net Zero Portal for voluntary registration and disclosure of climate commitments by Indian entities, alongside a National Action Plan on Climate Change dashboard that consolidates progress across national missions.',
 'The platform records voluntary commitments; it does not itself impose a legally binding net-zero obligation on every entity. The dashboard is relevant to national climate-mission monitoring.',
 'Participating entities can disclose greenhouse-gas emissions, targets and annual progress. The NAPCC Dashboard supports inter-ministerial monitoring of National Missions and their indicators.',
 'Union Minister launches India’s Net Zero Portal and NAPCC Dashboard on World Ozone Day 2026', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310737&lang=1&reg=3', 'Ministry of Environment, Forest and Climate Change / Press Information Bureau', '2026-09-16',
 '["The Net Zero Portal is for voluntary registration and disclosure of commitments.","The NAPCC Dashboard monitors National Missions on climate change.","Entities are encouraged to report Scope 1 and Scope 2 emissions; Scope 3 remains voluntary.","The platforms promote transparency and coordination."]'::jsonb,
 '[{"question":"Which scopes are entities encouraged to report?","answer":"Scope 1 and Scope 2; Scope 3 reporting remains voluntary."},{"question":"What does the dashboard consolidate?","answer":"Progress and indicators across National Missions under NAPCC."}]'::jsonb,
 '{"title":"Climate-governance dashboard","steps":["Entities disclose voluntary targets.","Portal records targets and progress.","Dashboard aggregates mission indicators.","Government uses information for coordination."]}'::jsonb, 'published', now()),
('2026-09-17-swachh-seva-aankalan', '2026-09-17',
 'Swachh Seva Aankalan starts rural sanitation self-assessment',
 'The Department of Drinking Water and Sanitation launched Swachh Seva Aankalan under Swachh Bharat Mission (Grameen) 2.0. It is an annual digital self-assessment framework at Gram Panchayat level, with Gram Sabha validation and review at district and State or UT levels.',
 'This is a decentralised-governance and sanitation-service-delivery update. It assesses rural sanitation service quality; it is not simply another name for an ODF declaration.',
 'The framework covers ODF sustainability, visual cleanliness, solid and liquid waste management, and operation-and-maintenance status. Village Water and Sanitation Committees, Gram Panchayats and Gram Sabhas are key parts of the assessment chain.',
 'Department of Drinking Water and Sanitation launches Swachh Seva Aankalan for Swachh Bharat Mission (Grameen)', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310773&lang=1&reg=3', 'Ministry of Jal Shakti / Press Information Bureau', '2026-09-16',
 '["Swachh Seva Aankalan is an annual Gram Panchayat-level digital self-assessment.","It operates under SBM (Grameen) 2.0.","Assessment includes ODF sustainability and solid and liquid waste management.","Gram Sabha validation adds community accountability."]'::jsonb,
 '[{"question":"At which local-government level is it conducted?","answer":"The Gram Panchayat level."},{"question":"Which forum validates the findings?","answer":"The concerned Gram Sabha."}]'::jsonb,
 '{"title":"Rural sanitation assessment","steps":["Panchayat and VWSC assess services.","ODF sustainability and waste management are reviewed.","Gram Sabha validates findings.","District and State bodies identify gaps."]}'::jsonb, 'published', now()),
('2026-09-17-cbfc-reconstitution', '2026-09-17',
 'Government reconstitutes the Central Board of Film Certification',
 'The Central Government reconstituted the Central Board of Film Certification with 18 members, with immediate effect for three years or until further orders. The action uses section 3 of the Cinematograph Act, 1952 and rule 3 of the Cinematograph (Certification) Rules, 2024.',
 'This is a culture-and-polity institutional update. CBFC certifies films under the statutory framework; it is not a general broadcasting or newspaper regulator.',
 'The stated tenure is limited by whichever comes earlier: three years or further orders. The legal basis is more useful for exam recall than the full member list.',
 'Government Reconstitutes Central Board of Film Certification with 18 Members', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2311000&lang=1&reg=3', 'Ministry of Information and Broadcasting / Press Information Bureau', '2026-09-16',
 '["CBFC was reconstituted with 18 members.","The stated term is three years or until further orders, whichever is earlier.","The action cites section 3 of the Cinematograph Act, 1952.","It also cites rule 3 of the Cinematograph (Certification) Rules, 2024."]'::jsonb,
 '[{"question":"Which Act is cited for the reconstitution?","answer":"The Cinematograph Act, 1952."},{"question":"Is CBFC a film-certification body or newspaper regulator?","answer":"A film-certification body."}]'::jsonb,
 '{"title":"CBFC legal basis","steps":["Cinematograph Act provides the framework.","Certification Rules set procedures.","Government reconstitutes the Board.","CBFC performs film certification."]}'::jsonb, 'published', now()),
('2026-09-17-shahzad-bhatti-network-uapa', '2026-09-17',
 'MHA declares the Shahzad Bhatti Network a terrorist organisation under UAPA',
 'The Ministry of Home Affairs declared the Shahzad Bhatti Network a terrorist organisation under the Unlawful Activities (Prevention) Act. The official release attributes to the group arms, explosives and narcotics smuggling, terror incitement and hateful digital content.',
 'This is relevant to internal security and the counter-terror legal framework. A UAPA designation is not the same as an ordinary criminal arrest, prosecution or court conviction.',
 'UAPA is a central law addressing unlawful activities and terrorism. A precise answer should identify the legal action and competent authority without claiming later investigation or trial outcomes.',
 'MHA declares Shahzad Bhatti Network as a terrorist organization under UAPA', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2311078&lang=1&reg=3', 'Ministry of Home Affairs / Press Information Bureau', '2026-09-16',
 '["The legal framework named is the Unlawful Activities (Prevention) Act (UAPA).","The action is a terrorist-organisation designation by MHA.","A designation differs from arrest, prosecution or conviction.","The release links the network to cross-border smuggling and terror incitement."]'::jsonb,
 '[{"question":"What does UAPA stand for?","answer":"Unlawful Activities (Prevention) Act."},{"question":"Is a UAPA designation identical to a court conviction?","answer":"No. They are legally distinct stages."}]'::jsonb,
 '{"title":"Counter-terror legal distinction","steps":["MHA acts under the UAPA framework.","A group receives a statutory designation.","Investigation and prosecution remain separate.","Courts determine judicial outcomes."]}'::jsonb, 'published', now()),
('2026-09-17-pm-vishwakarma-three-year-milestone', '2026-09-17',
 'PM Vishwakarma reports a three-year registration milestone',
 'The MSME Ministry reported that 30 lakh beneficiaries have completed three-stage verification and been registered under PM Vishwakarma. The scheme, launched on 17 September 2023, supports traditional artisans and craftspeople in 18 identified trades.',
 'The milestone connects verification, skilling, toolkits, concessional credit and marketing support. Registered beneficiaries are not automatically the same as those who have received every component.',
 'The release reports Basic Skill Training for about 24.50 lakh Vishwakarmas, loan support to 6.18 lakh beneficiaries and 18.15 lakh modern toolkits delivered.',
 'PM Vishwakarma Completes Three Years: 30 Lakh Artisans Registered Under the Scheme', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310751&lang=1&reg=3', 'Ministry of Micro, Small and Medium Enterprises / Press Information Bureau', '2026-09-16',
 '["PM Vishwakarma was launched on 17 September 2023.","It covers traditional artisans and craftspeople in 18 identified trades.","The reported 30 lakh registrations followed a three-stage verification process.","Support includes recognition, skills, toolkits, credit and marketing support."]'::jsonb,
 '[{"question":"How many identified trades does the scheme cover?","answer":"Eighteen."},{"question":"Does registration prove that all scheme components were received?","answer":"No. Registration and receipt of individual supports are separate stages."}]'::jsonb,
 '{"title":"PM Vishwakarma support path","steps":["Artisan completes verification.","Registration provides recognition.","Training and toolkits build capability.","Credit and market links support livelihoods."]}'::jsonb, 'published', now()),
('2026-09-17-india-mercosur-electronic-certificates', '2026-09-17',
 'India and MERCOSUR sign a protocol for electronic certificates of origin',
 'India and MERCOSUR signed the First Additional Protocol to their Preferential Trade Agreement to recognise electronic Certificates of Origin with the same legal validity as paper certificates. The protocol amends article 16 of Annex III on Rules of Origin.',
 'This is a paperless-trade and customs-modernisation step. It is signed, but enters into force only after the parties complete internal procedures and notify one another.',
 'The India-MERCOSUR PTA was signed in 2004 and entered into force in 2009. It provides preferential tariff concessions on 450 tariff lines by India and 452 by the MERCOSUR side, according to the release.',
 'India and MERCOSUR Sign First Additional Protocol to Facilitate Electronic Certificates of Origin', 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2310083&lang=1&reg=3', 'Ministry of Commerce and Industry / Press Information Bureau', '2026-09-14',
 '["The First Additional Protocol covers electronic Certificates of Origin.","It amends article 16 of Annex III on Rules of Origin.","Electronic and paper certificates are to have equal legal validity.","Entry into force follows internal procedures and notification."]'::jsonb,
 '[{"question":"What document is covered by the protocol?","answer":"The Certificate of Origin, including its electronic form."},{"question":"Did it enter into force immediately on signature?","answer":"No. Internal procedures and notification are required."}]'::jsonb,
 '{"title":"Paperless preferential-trade step","steps":["India and MERCOSUR sign the protocol.","Article 16 on Rules of Origin is amended.","Electronic certificates gain equal legal validity.","Internal procedures precede entry into force."]}'::jsonb, 'published', now())
on conflict (slug) do update set
  title = excluded.title, summary = excluded.summary, why_it_matters = excluded.why_it_matters,
  background = excluded.background, source_title = excluded.source_title, source_url = excluded.source_url,
  source_publisher = excluded.source_publisher, source_published_on = excluded.source_published_on,
  prelims_takeaways = excluded.prelims_takeaways, quick_check = excluded.quick_check,
  visual_data = excluded.visual_data, status = excluded.status, reviewed_at = excluded.reviewed_at,
  updated_at = now();

insert into public.current_affairs_exam_tags (brief_id, exam_id)
select briefs.id, exams.id from public.current_affairs_briefs briefs cross join public.exams exams
where briefs.slug like '2026-09-17-%' and exams.slug in ('cuet', 'ssc-cgl', 'uppsc-ro-aro', 'up-secretariat-ro-aro')
on conflict do nothing;
