-- Delhi Police Constable: replace compound leaf pages with a genuinely
-- navigable learning map.  SSC publishes an indicative syllabus; chapter and
-- topic labels below are ExamGrind's original study structure, not a claim
-- that SSC publishes these exact chapter counts. This migration is additive
-- except for tightening the names of existing compound pages, so learner
-- history and existing links remain valid.

-- A topic must be one thing a learner can study, practise and repair.  Rename
-- older catch-all pages before adding the missing individual focus pages.
update public.topics t
set name = v.name,
    description = format('Build %s for Delhi Police Constable objective practice.', v.name)
from (values
  ('dp-gk','indian-geography','physiography-rivers-climate','Indian Physiographic Divisions'),
  ('dp-gk','indian-geography','soils-agriculture-minerals','Soil Types and Distribution'),
  ('dp-gk','indian-geography','states-neighbours-mapping','States, Capitals and Borders'),
  ('dp-gk','world-geography-environment','earth-atmosphere-oceans','Earth Structure and Interior'),
  ('dp-gk','world-geography-environment','ecology-biodiversity-pollution','Ecosystems and Food Chains'),
  ('dp-gk','indian-polity','president-parliament-judiciary','Parliament: Houses, Sessions and Law-making'),
  ('dp-gk','indian-polity','centre-state-constitutional-bodies','Centre-State Relations'),
  ('dp-gk','biology-human-health','cell-plant-animal-basics','Cell Structure and Organelles'),
  ('dp-gk','biology-human-health','human-systems-disease-nutrition','Digestive System and Nutrition'),
  ('dp-quant','time-work-speed-distance','work-efficiency-pipes-cisterns','Work and Efficiency'),
  ('dp-quant','time-work-speed-distance','speed-distance-trains-boats','Speed, Time and Distance'),
  ('dp-quant','mensuration-data-interpretation','two-dimensional-three-dimensional-mensuration','Data Interpretation: Tables and Graphs'),
  ('dp-reasoning','directions-relations-ranking','turns-distance-final-direction','Directions and Turns'),
  ('dp-reasoning','directions-relations-ranking','family-tree-coded-relations','Coded Blood Relations'),
  ('dp-reasoning','directions-relations-ranking','rank-position-linear-arrangement','Ranking and Position'),
  ('dp-computer','hardware-memory-storage','primary-secondary-cloud-storage','Primary and Secondary Memory'),
  ('dp-computer','internet-networks-cyber-safety','internet-browser-email-networks','Internet and Web Basics'),
  ('dp-computer','office-tools-shortcuts','word-excel-presentation-basics','MS Office: Core Tools')
) as v(subject_id, chapter_slug, topic_slug, name)
join public.chapters c on c.subject_id = v.subject_id and c.slug = v.chapter_slug
where t.chapter_id = c.id and t.slug = v.topic_slug;

with raw(subject_id, chapter_slug, name, slug, ord) as (values
  -- General Knowledge: Indian history, culture and geography
  ('dp-gk','ancient-medieval-india','Prehistoric India and Indus Valley','prehistory-indus-valley',5),
  ('dp-gk','ancient-medieval-india','Vedic Literature and Early Kingdoms','vedic-literature-early-kingdoms',6),
  ('dp-gk','ancient-medieval-india','Buddhism and Jainism','buddhism-jainism',7),
  ('dp-gk','ancient-medieval-india','Mauryan Administration and Ashoka','mauryan-administration-ashoka',8),
  ('dp-gk','ancient-medieval-india','Gupta Age and Regional Kingdoms','gupta-regional-kingdoms',9),
  ('dp-gk','ancient-medieval-india','Bhakti, Sufi and Medieval Culture','bhakti-sufi-medieval-culture',10),
  ('dp-gk','modern-india-freedom-movement','European Companies and British Expansion','european-companies-british-expansion',5),
  ('dp-gk','modern-india-freedom-movement','Social and Religious Reform Movements','social-religious-reform-movements',6),
  ('dp-gk','modern-india-freedom-movement','Revolt of 1857: Causes and Leaders','revolt-1857-causes-leaders',7),
  ('dp-gk','modern-india-freedom-movement','Congress Sessions and Early Nationalism','congress-sessions-early-nationalism',8),
  ('dp-gk','modern-india-freedom-movement','Gandhian Movements','gandhian-movements',9),
  ('dp-gk','modern-india-freedom-movement','Constitutional Acts and Viceroys','constitutional-acts-viceroys',10),
  ('dp-gk','indian-art-culture','Indian Architecture: Temple, Buddhist and Indo-Islamic','indian-architecture',5),
  ('dp-gk','indian-art-culture','Classical Dances and Folk Dances','classical-folk-dances-deep',6),
  ('dp-gk','indian-art-culture','Classical Music and Instruments','classical-music-instruments',7),
  ('dp-gk','indian-art-culture','Paintings, Puppetry and Theatre','paintings-puppetry-theatre',8),
  ('dp-gk','indian-art-culture','Literature, Languages and UNESCO Heritage','literature-languages-unesco-heritage',9),
  ('dp-gk','indian-geography','The Himalayas and Northern Mountains','himalayas-northern-mountains',4),
  ('dp-gk','indian-geography','Northern Plains and Major Landforms','northern-plains-landforms',5),
  ('dp-gk','indian-geography','Peninsular Plateau and Deccan','peninsular-plateau-deccan',6),
  ('dp-gk','indian-geography','Coastal Plains and Indian Islands','coastal-plains-indian-islands',7),
  ('dp-gk','indian-geography','Himalayan River Systems','himalayan-river-systems',8),
  ('dp-gk','indian-geography','Peninsular River Systems','peninsular-river-systems',9),
  ('dp-gk','indian-geography','Indian Monsoon and Seasons','indian-monsoon-seasons',10),
  ('dp-gk','indian-geography','Natural Vegetation and Wildlife Regions','natural-vegetation-wildlife-regions',11),
  ('dp-gk','indian-geography','Agriculture: Crops and Seasons','agriculture-crops-seasons',12),
  ('dp-gk','indian-geography','Minerals, Energy Resources and Industries','minerals-energy-industries',13),
  ('dp-gk','indian-geography','India Map Practice: States, Cities and Neighbours','india-map-states-cities-neighbours',14),
  ('dp-gk','world-geography-environment','Latitude, Longitude and Time Zones','latitude-longitude-time-zones-deep',5),
  ('dp-gk','world-geography-environment','Rocks, Volcanoes and Earthquakes','rocks-volcanoes-earthquakes',6),
  ('dp-gk','world-geography-environment','Atmosphere, Pressure Belts and Winds','atmosphere-pressure-belts-winds',7),
  ('dp-gk','world-geography-environment','Oceans, Currents and Tides','oceans-currents-tides',8),
  ('dp-gk','world-geography-environment','Biomes and Biodiversity Hotspots','biomes-biodiversity-hotspots',9),
  ('dp-gk','world-geography-environment','Pollution, Climate Change and Conservation','pollution-climate-conservation',10),
  -- Polity, governance, economy and science
  ('dp-gk','indian-polity','Making of the Constitution and the Preamble','constitution-making-preamble',4),
  ('dp-gk','indian-polity','Fundamental Rights, Duties and DPSP','rights-duties-dpsp-deep',5),
  ('dp-gk','indian-polity','President, Vice-President and Prime Minister','president-vice-president-prime-minister',6),
  ('dp-gk','indian-polity','Supreme Court, High Courts and Judicial Review','supreme-high-courts-judicial-review',7),
  ('dp-gk','indian-polity','Constitutional Bodies: EC, CAG, UPSC and Finance Commission','constitutional-bodies-core',8),
  ('dp-gk','indian-polity','Amendments, Emergency and Schedules','amendments-emergency-schedules',9),
  ('dp-gk','governance-public-institutions','Panchayati Raj and Urban Local Bodies','panchayati-raj-urban-local-bodies',5),
  ('dp-gk','governance-public-institutions','Parliamentary Committees and Public Accountability','parliamentary-committees-accountability',6),
  ('dp-gk','governance-public-institutions','Flagship Government Schemes','flagship-government-schemes',7),
  ('dp-gk','governance-public-institutions','National and International Organisations','national-international-organisations',8),
  ('dp-gk','indian-economy','National Income and Economic Sectors','national-income-economic-sectors',5),
  ('dp-gk','indian-economy','Inflation, Monetary Policy and RBI','inflation-monetary-policy-rbi',6),
  ('dp-gk','indian-economy','Banking, Digital Payments and Financial Inclusion','banking-digital-payments-financial-inclusion',7),
  ('dp-gk','indian-economy','Budget, Taxes and Fiscal Deficit','budget-taxes-fiscal-deficit',8),
  ('dp-gk','indian-economy','External Sector, Trade and Exchange Rate','external-sector-trade-exchange-rate',9),
  ('dp-gk','everyday-physics','Units, Measurement and Motion','units-measurement-motion',5),
  ('dp-gk','everyday-physics','Force, Gravitation and Pressure','force-gravitation-pressure',6),
  ('dp-gk','everyday-physics','Work, Energy and Power','work-energy-power',7),
  ('dp-gk','everyday-physics','Heat and Thermodynamics in Daily Life','heat-thermodynamics-daily-life',8),
  ('dp-gk','everyday-physics','Light, Lenses and Human Eye','light-lenses-human-eye',9),
  ('dp-gk','everyday-physics','Sound and Electricity','sound-electricity',10),
  ('dp-gk','everyday-chemistry','Atoms, Molecules and Atomic Structure','atoms-molecules-atomic-structure',5),
  ('dp-gk','everyday-chemistry','Periodic Table and Chemical Bonding','periodic-table-chemical-bonding',6),
  ('dp-gk','everyday-chemistry','Acids, Bases, Salts and pH','acids-bases-salts-ph',7),
  ('dp-gk','everyday-chemistry','Metals, Non-metals and Alloys','metals-nonmetals-alloys',8),
  ('dp-gk','everyday-chemistry','Carbon Compounds and Everyday Materials','carbon-compounds-everyday-materials',9),
  ('dp-gk','biology-human-health','Plant Cell, Animal Cell and Cell Division','plant-animal-cell-division',5),
  ('dp-gk','biology-human-health','Plant Tissues, Photosynthesis and Transport','plant-tissues-photosynthesis-transport',6),
  ('dp-gk','biology-human-health','Human Digestive and Respiratory Systems','digestive-respiratory-systems',7),
  ('dp-gk','biology-human-health','Circulatory, Excretory and Nervous Systems','circulatory-excretory-nervous-systems',8),
  ('dp-gk','biology-human-health','Diseases, Immunity and Vaccination','diseases-immunity-vaccination',9),
  ('dp-gk','biology-human-health','Nutrition, Vitamins and Deficiency Diseases','nutrition-vitamins-deficiency-diseases',10),
  ('dp-gk','technology-space-defence','ISRO Missions and Satellites','isro-missions-satellites',5),
  ('dp-gk','technology-space-defence','Defence Commands, Missiles and Exercises','defence-commands-missiles-exercises',6),
  ('dp-gk','technology-space-defence','Digital Technology, AI and Cyber Basics','digital-technology-ai-cyber-basics',7),
  ('dp-gk','sports-awards-books','Sports Cups, Venues and Governing Bodies','sports-cups-venues-governing-bodies',5),
  ('dp-gk','sports-awards-books','National and International Awards','national-international-awards-deep',6),
  ('dp-gk','sports-awards-books','Books, Authors, Days and Themes','books-authors-days-themes',7),
  ('dp-gk','current-affairs-method','Appointments and Resignations','appointments-resignations',3),
  ('dp-gk','current-affairs-method','Summits, Reports and Indices','summits-reports-indices',4),
  ('dp-gk','current-affairs-method','Government Schemes and Policy Decisions','current-affairs-schemes-policy',5),
  ('dp-gk','current-affairs-method','Sports, Awards, Obituaries and Books','current-affairs-sports-awards-books',6),
  ('dp-gk','general-science','Physics: Motion, Force and Energy','science-physics-motion-force-energy',5),
  ('dp-gk','general-science','Physics: Light, Sound, Heat and Electricity','science-physics-light-sound-heat-electricity',6),
  ('dp-gk','general-science','Chemistry: Atoms, Acids, Bases and Salts','science-chemistry-atoms-acids-bases-salts',7),
  ('dp-gk','general-science','Biology: Cell, Human Systems and Health','science-biology-cell-human-systems-health',8),
  ('dp-gk','general-science','Environment, Ecology and Pollution','science-environment-ecology-pollution',9),
  -- Quantitative aptitude: make calculation areas atomic enough to practise
  ('dp-quant','number-system-simplification','Place Value, Integers and Number Properties','place-value-integers-number-properties',5),
  ('dp-quant','number-system-simplification','Divisibility Rules and Remainders','divisibility-rules-remainders',6),
  ('dp-quant','number-system-simplification','BODMAS and Simplification','bodmas-simplification-deep',7),
  ('dp-quant','percentages-ratio-average','Percentage Change and Successive Percentage','percentage-change-successive-percentage',5),
  ('dp-quant','percentages-ratio-average','Ratio, Proportion and Comparison','ratio-proportion-comparison',6),
  ('dp-quant','percentages-ratio-average','Average and Weighted Average','average-weighted-average',7),
  ('dp-quant','profit-loss-interest','Cost Price, Selling Price and Profit Percentage','cost-price-selling-price-profit',5),
  ('dp-quant','profit-loss-interest','Discount, Marked Price and Successive Discount','discount-marked-price-successive-discount',6),
  ('dp-quant','profit-loss-interest','Simple Interest and Compound Interest','simple-compound-interest-deep',7),
  ('dp-quant','time-work-speed-distance','Work Efficiency and Men-Days','work-efficiency-men-days',5),
  ('dp-quant','time-work-speed-distance','Pipes, Cisterns and Leakage','pipes-cisterns-leakage-deep',6),
  ('dp-quant','time-work-speed-distance','Relative Speed and Average Speed','relative-average-speed',7),
  ('dp-quant','mensuration-data-interpretation','Tables and Bar Graphs','tables-bar-graphs-deep',5),
  ('dp-quant','mensuration-data-interpretation','Pie Charts and Percentage Data','pie-charts-percentage-data',6),
  ('dp-quant','mensuration-data-interpretation','Line Graphs and Data Comparison','line-graphs-data-comparison',7),
  ('dp-quant','ratio-proportion-partnership','Ratio and Proportion','ratio-proportion-deep',5),
  ('dp-quant','ratio-proportion-partnership','Partnership and Distribution','partnership-distribution-deep',6),
  ('dp-quant','ratio-proportion-partnership','Mixture and Alligation','mixture-alligation-deep',7),
  ('dp-quant','algebra','Algebraic Identities','algebraic-identities-deep',5),
  ('dp-quant','algebra','Linear Equations and Graphs','linear-equations-graphs',6),
  ('dp-quant','algebra','Quadratic Equations and Factorisation','quadratic-equations-factorisation',7),
  ('dp-quant','geometry','Lines, Angles and Transversals','lines-angles-transversals',5),
  ('dp-quant','geometry','Triangles: Congruence and Similarity','triangles-congruence-similarity',6),
  ('dp-quant','geometry','Quadrilaterals, Polygons and Circles','quadrilaterals-polygons-circles',7),
  ('dp-quant','mensuration','Perimeter and Area of 2D Figures','perimeter-area-2d-figures',5),
  ('dp-quant','mensuration','Surface Area and Volume of Solids','surface-area-volume-solids',6),
  ('dp-quant','mensuration','Prism, Cylinder, Cone and Sphere','prism-cylinder-cone-sphere',7),
  ('dp-quant','trigonometry-heights-distances','Trigonometric Ratios and Standard Values','trigonometric-ratios-standard-values',5),
  ('dp-quant','trigonometry-heights-distances','Complementary Angles and Identities','complementary-angles-identities',6),
  ('dp-quant','trigonometry-heights-distances','Heights and Distances Applications','heights-distances-applications',7),
  -- Reasoning and computer are decomposed the same way: one method per page
  ('dp-reasoning','analogy-classification','Word and Meaning Analogy','word-meaning-analogy-deep',3),
  ('dp-reasoning','analogy-classification','Number and Symbol Analogy','number-symbol-analogy',4),
  ('dp-reasoning','analogy-classification','Figure Analogy and Classification','figure-analogy-classification-deep',5),
  ('dp-reasoning','series-coding','Number Series','number-series-deep',3),
  ('dp-reasoning','series-coding','Alphabet Series','alphabet-series-deep',4),
  ('dp-reasoning','series-coding','Coding-Decoding Rules','coding-decoding-rules',5),
  ('dp-reasoning','directions-relations-ranking','Distance and Final Position','distance-final-position',4),
  ('dp-reasoning','directions-relations-ranking','Blood Relations: Family Tree Method','blood-relations-family-tree-method',5),
  ('dp-reasoning','directions-relations-ranking','Linear Arrangement and Ranking','linear-arrangement-ranking',6),
  ('dp-reasoning','syllogism-venn','Venn Diagram Representation','venn-diagram-representation',4),
  ('dp-reasoning','syllogism-venn','Syllogism Conclusions','syllogism-conclusions',5),
  ('dp-reasoning','syllogism-venn','Statement, Assumption and Conclusion','statement-assumption-conclusion-deep',6),
  ('dp-reasoning','word-formation-dictionary-order','Letter Position and Alphabet Order','letter-position-alphabet-order',5),
  ('dp-reasoning','word-formation-dictionary-order','Dictionary Order','dictionary-order-deep',6),
  ('dp-reasoning','word-formation-dictionary-order','Word Formation and Meaningful Arrangement','word-formation-meaningful-arrangement',7),
  ('dp-reasoning','directions-distance','Turns and Direction Sense','turns-direction-sense',5),
  ('dp-reasoning','directions-distance','Distance and Coordinate Method','distance-coordinate-method',6),
  ('dp-reasoning','blood-relations','Direct and Coded Blood Relations','direct-coded-blood-relations',5),
  ('dp-reasoning','blood-relations','Pointing and Generation-based Relations','pointing-generation-relations',6),
  ('dp-reasoning','ranking-order-seating','Ranking From Both Ends','ranking-both-ends',5),
  ('dp-reasoning','ranking-order-seating','Linear and Circular Seating Basics','linear-circular-seating-basics',6),
  ('dp-reasoning','venn-set-relations','Set Overlap and Counting','set-overlap-counting',5),
  ('dp-reasoning','venn-set-relations','Classification Through Venn Diagrams','classification-venn-diagrams',6),
  ('dp-reasoning','syllogism-statement-logic','Syllogism Possibility Cases','syllogism-possibility-cases',5),
  ('dp-reasoning','syllogism-statement-logic','Statement and Conclusion Logic','statement-conclusion-logic',6),
  ('dp-reasoning','calendar-clock-age','Odd Days and Calendar Method','odd-days-calendar-method',5),
  ('dp-reasoning','calendar-clock-age','Clock Angles','clock-angles-deep',6),
  ('dp-reasoning','calendar-clock-age','Age Equations','age-equations-deep',7),
  ('dp-reasoning','mathematical-operations','Operator Substitution','operator-substitution-deep-2',5),
  ('dp-reasoning','mathematical-operations','Equation Balance','equation-balance-deep',6),
  ('dp-reasoning','mathematical-operations','Symbol and Number Operations','symbol-number-operations',7),
  ('dp-reasoning','figure-analogy-classification','Figure Analogy','figure-analogy-deep-2',5),
  ('dp-reasoning','figure-analogy-classification','Figure Classification','figure-classification-deep',6),
  ('dp-reasoning','figure-analogy-classification','Figure Completion','figure-completion-deep',7),
  ('dp-reasoning','mirror-water-embedded-figures','Mirror Images','mirror-images-deep-2',5),
  ('dp-reasoning','mirror-water-embedded-figures','Water Images','water-images-deep',6),
  ('dp-reasoning','mirror-water-embedded-figures','Embedded Figures','embedded-figures-deep',7),
  ('dp-reasoning','paper-folding-cube-dice','Paper Folding and Cutting','paper-folding-cutting-deep-2',5),
  ('dp-reasoning','paper-folding-cube-dice','Cube Rules','cube-rules-deep',6),
  ('dp-reasoning','paper-folding-cube-dice','Dice Rules and Opposite Faces','dice-rules-opposite-faces',7),
  ('dp-reasoning','non-verbal-reasoning','Mirror Images','nonverbal-mirror-images',5),
  ('dp-reasoning','non-verbal-reasoning','Water Images and Embedded Figures','nonverbal-water-images-embedded-figures',6),
  ('dp-reasoning','non-verbal-reasoning','Paper Folding, Cube and Dice Rules','nonverbal-paper-folding-cube-dice',7),
  ('dp-computer','computer-fundamentals','Input and Output Devices','input-output-devices',5),
  ('dp-computer','computer-fundamentals','CPU, ALU and Control Unit','cpu-alu-control-unit',6),
  ('dp-computer','computer-fundamentals','Computer Generations','computer-generations-deep',7),
  ('dp-computer','hardware-memory-storage','Primary Memory: RAM and ROM','primary-memory-ram-rom',5),
  ('dp-computer','hardware-memory-storage','Secondary Storage Devices','secondary-storage-devices',6),
  ('dp-computer','hardware-memory-storage','Cloud Storage and Backup','cloud-storage-backup',7),
  ('dp-computer','operating-systems-files','Operating System Functions','operating-system-functions-deep-2',5),
  ('dp-computer','operating-systems-files','Files, Folders and Extensions','files-folders-extensions-deep',6),
  ('dp-computer','operating-systems-files','System, Application and Utility Software','system-application-utility-software-deep',7),
  ('dp-computer','internet-networks-cyber-safety','Browser, Search Engine and URL','browser-search-engine-url-deep',5),
  ('dp-computer','internet-networks-cyber-safety','Email, Protocols and Attachments','email-protocols-attachments',6),
  ('dp-computer','internet-networks-cyber-safety','Networks and Network Devices','networks-network-devices',7),
  ('dp-computer','internet-networks-cyber-safety','Malware, Phishing and Safe Browsing','malware-phishing-safe-browsing',8),
  ('dp-computer','office-tools-shortcuts','MS Word: Formatting and Page Layout','ms-word-formatting-page-layout',5),
  ('dp-computer','office-tools-shortcuts','MS Excel: Cells, Formulae and Functions','ms-excel-cells-formulae-functions',6),
  ('dp-computer','office-tools-shortcuts','MS PowerPoint: Slides and Views','ms-powerpoint-slides-views',7),
  ('dp-computer','office-tools-shortcuts','Keyboard Shortcuts and File Commands','keyboard-shortcuts-file-commands',8),
  ('dp-computer','computer-basics-generations','Computer Types and Characteristics','computer-types-characteristics',5),
  ('dp-computer','computer-basics-generations','Hardware, Software and Firmware','hardware-software-firmware',6),
  ('dp-computer','computer-basics-generations','Computer Generations','computer-generations-basics-deep',7),
  ('dp-computer','software-operating-systems','System Software and Operating Systems','system-software-operating-systems',5),
  ('dp-computer','software-operating-systems','Application and Utility Software','application-utility-software-deep',6),
  ('dp-computer','software-operating-systems','Open-source, Proprietary and Licences','open-source-proprietary-licences',7),
  ('dp-computer','number-systems-data-representation','Bits, Bytes and Storage Units','bits-bytes-storage-units',5),
  ('dp-computer','number-systems-data-representation','Binary and Decimal Conversion','binary-decimal-conversion-deep',6),
  ('dp-computer','number-systems-data-representation','Character Codes and Data Representation','character-codes-data-representation',7),
  ('dp-computer','internet-web-email','Internet, WWW and Web Browsers','internet-www-web-browsers',5),
  ('dp-computer','internet-web-email','Search Engines, URL and Hyperlinks','search-engines-url-hyperlinks',6),
  ('dp-computer','internet-web-email','Email Fields, Protocols and Attachments','email-fields-protocols-attachments',7),
  ('dp-computer','networks-communication','LAN, MAN and WAN','lan-man-wan-deep',5),
  ('dp-computer','networks-communication','Network Topologies and Devices','network-topologies-devices',6),
  ('dp-computer','networks-communication','Communication Media and Protocols','communication-media-protocols-deep',7),
  ('dp-computer','cyber-security-digital-safety','Malware and Antivirus','malware-antivirus-deep-2',5),
  ('dp-computer','cyber-security-digital-safety','Phishing, Passwords and MFA','phishing-passwords-mfa-deep',6),
  ('dp-computer','cyber-security-digital-safety','Privacy, Digital Footprint and Safe Browsing','privacy-digital-footprint-safe-browsing',7),
  ('dp-computer','ms-word','Word Interface and File Operations','word-interface-file-operations-deep',5),
  ('dp-computer','ms-word','Text, Paragraph and Page Formatting','word-text-paragraph-page-formatting-deep',6),
  ('dp-computer','ms-word','Tables, Mail Merge and Print','word-tables-mail-merge-print-deep',7),
  ('dp-computer','ms-excel','Cells, References and Formulas','excel-cells-references-formulas-deep',5),
  ('dp-computer','ms-excel','Functions, Sorting and Filtering','excel-functions-sorting-filtering-deep',6),
  ('dp-computer','ms-excel','Charts and Data Tools','excel-charts-data-tools',7),
  ('dp-computer','ms-powerpoint-keyboard-shortcuts','Slides, Themes and Views','powerpoint-slides-themes-views-deep',5),
  ('dp-computer','ms-powerpoint-keyboard-shortcuts','Transitions, Animation and Slide Show','powerpoint-transitions-animation-slide-show-deep',6),
  ('dp-computer','ms-powerpoint-keyboard-shortcuts','Keyboard Shortcuts','keyboard-shortcuts-deep',7)
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, r.name, r.slug,
       format('Build %s for Delhi Police Constable objective practice.', r.name), r.ord
from raw r
join public.chapters c on c.subject_id = r.subject_id and c.slug = r.chapter_slug
on conflict (chapter_id, slug) do update
  set name = excluded.name,
      description = excluded.description,
      order_index = excluded.order_index;

-- A few early chapter records used legacy slugs, so cover them by their
-- canonical display name rather than creating a second, hidden chapter.
with legacy_raw(subject_id, chapter_name, name, slug, ord) as (values
  ('dp-gk','Modern India & Freedom Movement','Reform Movements and the Revolt of 1857','legacy-modern-reform-1857',5),
  ('dp-gk','Modern India & Freedom Movement','Congress Sessions and Early Nationalism','legacy-modern-congress-early-nationalism',6),
  ('dp-gk','Modern India & Freedom Movement','Gandhian Movements, Acts and Viceroys','legacy-modern-gandhian-acts-viceroys',7),
  ('dp-quant','HCF, LCM, Surds & Indices','Prime Factorisation, HCF and LCM','legacy-hcf-lcm-prime-factorisation',5),
  ('dp-quant','HCF, LCM, Surds & Indices','Surds, Indices and Rationalisation','legacy-surds-indices-rationalisation',6),
  ('dp-quant','HCF, LCM, Surds & Indices','Divisibility Rules and Unit Digit','legacy-divisibility-unit-digit',7),
  ('dp-quant','Decimals, Fractions & Recurring Values','Fraction-Decimal Conversion','legacy-fraction-decimal-conversion',5),
  ('dp-quant','Decimals, Fractions & Recurring Values','Recurring Decimals and Comparison','legacy-recurring-decimals-comparison',6),
  ('dp-quant','Decimals, Fractions & Recurring Values','Operations and Approximation','legacy-decimal-operations-approximation',7),
  ('dp-quant','Simple & Compound Interest','Principal, Rate and Time','legacy-interest-principal-rate-time',5),
  ('dp-quant','Simple & Compound Interest','Compound Interest Growth','legacy-compound-interest-growth',6),
  ('dp-quant','Simple & Compound Interest','Difference Between SI and CI','legacy-si-ci-difference',7),
  ('dp-quant','Pipes & Cisterns','Efficiency and Work Rates','legacy-pipes-efficiency-work-rates',5),
  ('dp-quant','Pipes & Cisterns','Inlet, Outlet and Leakage','legacy-pipes-inlet-outlet-leakage',6),
  ('dp-quant','Pipes & Cisterns','Combined Pipe Problems','legacy-pipes-combined-problems',7),
  ('dp-quant','Time, Speed & Distance','Speed Conversion and Relative Speed','legacy-speed-conversion-relative-speed',5),
  ('dp-quant','Time, Speed & Distance','Average Speed','legacy-average-speed',6),
  ('dp-quant','Time, Speed & Distance','Distance-Time Graph Basics','legacy-distance-time-graphs',7),
  ('dp-quant','Trains, Boats & Streams','Trains and Platform Problems','legacy-trains-platforms',5),
  ('dp-quant','Trains, Boats & Streams','Boats and Streams','legacy-boats-streams',6),
  ('dp-quant','Trains, Boats & Streams','Relative Speed Applications','legacy-trains-boats-relative-speed',7)
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, r.name, r.slug,
       format('Build %s for Delhi Police Constable objective practice.', r.name), r.ord
from legacy_raw r
join public.chapters c on c.subject_id = r.subject_id and c.name = r.chapter_name
on conflict (chapter_id, slug) do update
  set name = excluded.name,
      description = excluded.description,
      order_index = excluded.order_index;
