-- Migration 034 — SSC CGL topic depth across all 4 subjects
-- 65 chapters × 6 topics = 390 topic rows. Subject-specific (single-skill chapters).
-- Applied 2026-06-24. 58 of 65 chapters seeded (7 patched in 035 — chapter names not visible during initial authoring).

delete from public.topics t
 using public.chapters c, public.subjects s
 where t.chapter_id = c.id
   and c.subject_id = s.id
   and s.id in ('ssc-english','ssc-quant','ssc-reasoning','ssc-ga');

with raw(subject_id, chapter_name, topic_name, topic_slug, ord) as (values

  -- SSC ENGLISH
  ('ssc-english','Active & Passive Voice','Simple Tense Conversions','simple',1),
  ('ssc-english','Active & Passive Voice','Perfect Tense Conversions','perfect',2),
  ('ssc-english','Active & Passive Voice','Modal Verb Voice Changes','modal',3),
  ('ssc-english','Active & Passive Voice','Imperative Voice','imperative',4),
  ('ssc-english','Active & Passive Voice','Complex Sentence Voice','complex',5),
  ('ssc-english','Active & Passive Voice','High-Frequency PYQs','pyq',6),

  ('ssc-english','Direct & Indirect Speech','Statement Reporting','statement',1),
  ('ssc-english','Direct & Indirect Speech','Question Reporting','question',2),
  ('ssc-english','Direct & Indirect Speech','Imperative Reporting','imperative',3),
  ('ssc-english','Direct & Indirect Speech','Exclamatory Reporting','exclamatory',4),
  ('ssc-english','Direct & Indirect Speech','Time & Place References','time-place',5),
  ('ssc-english','Direct & Indirect Speech','Modal Verb Reporting','modal',6),

  ('ssc-english','Reading Comprehension','Main Idea','main-idea',1),
  ('ssc-english','Reading Comprehension','Inference','inference',2),
  ('ssc-english','Reading Comprehension','Detail Questions','detail',3),
  ('ssc-english','Reading Comprehension','Vocabulary in Passage','vocab',4),
  ('ssc-english','Reading Comprehension','Author Tone & Purpose','tone',5),
  ('ssc-english','Reading Comprehension','Title & Summary','title',6),

  ('ssc-english','Cloze Test','Theme-Based Cloze','theme',1),
  ('ssc-english','Cloze Test','News-Based Cloze','news',2),
  ('ssc-english','Cloze Test','Vocabulary Choice','vocab',3),
  ('ssc-english','Cloze Test','Grammar Fill-In','grammar',4),
  ('ssc-english','Cloze Test','Connector Words','connectors',5),
  ('ssc-english','Cloze Test','PYQ Patterns','pyq',6),

  ('ssc-english','Fill in the Blanks','Single Blank Vocab','single-vocab',1),
  ('ssc-english','Fill in the Blanks','Double Blank Vocab','double',2),
  ('ssc-english','Fill in the Blanks','Preposition Fill','prep',3),
  ('ssc-english','Fill in the Blanks','Article Fill','article',4),
  ('ssc-english','Fill in the Blanks','Conjunction Fill','conjunction',5),
  ('ssc-english','Fill in the Blanks','Tense Fill','tense',6),

  ('ssc-english','Idioms & Phrases','Body-Part Idioms','body',1),
  ('ssc-english','Idioms & Phrases','Animal Idioms','animal',2),
  ('ssc-english','Idioms & Phrases','Colour Idioms','colour',3),
  ('ssc-english','Idioms & Phrases','Phrasal Verbs','phrasal',4),
  ('ssc-english','Idioms & Phrases','Origin-Based Idioms','origin',5),
  ('ssc-english','Idioms & Phrases','SSC High-Frequency','pyq',6),

  ('ssc-english','One Word Substitution','People & Personality','people',1),
  ('ssc-english','One Word Substitution','Phobias & Manias','phobias',2),
  ('ssc-english','One Word Substitution','Government & Politics','govt',3),
  ('ssc-english','One Word Substitution','Religion & Belief','religion',4),
  ('ssc-english','One Word Substitution','Place & Position','place',5),
  ('ssc-english','One Word Substitution','Action & Behaviour','action',6),

  ('ssc-english','Para Jumbles','Theme Detection','theme',1),
  ('ssc-english','Para Jumbles','Anchor Sentence ID','anchor',2),
  ('ssc-english','Para Jumbles','Pronoun & Reference Cues','pronoun',3),
  ('ssc-english','Para Jumbles','Connector Cues','connector',4),
  ('ssc-english','Para Jumbles','Chronological Cues','chronological',5),
  ('ssc-english','Para Jumbles','PYQ Patterns','pyq',6),

  ('ssc-english','Sentence Completion','Vocabulary Choice','vocab',1),
  ('ssc-english','Sentence Completion','Grammar Choice','grammar',2),
  ('ssc-english','Sentence Completion','Tense Consistency','tense',3),
  ('ssc-english','Sentence Completion','Connector Choice','connector',4),
  ('ssc-english','Sentence Completion','Parallelism','parallelism',5),
  ('ssc-english','Sentence Completion','Logical Closure','logical',6),

  ('ssc-english','Sentence Improvement','Grammar Errors','grammar',1),
  ('ssc-english','Sentence Improvement','Tense Errors','tense',2),
  ('ssc-english','Sentence Improvement','Pronoun Errors','pronoun',3),
  ('ssc-english','Sentence Improvement','Subject-Verb Agreement','sva',4),
  ('ssc-english','Sentence Improvement','Wordy Phrases','wordy',5),
  ('ssc-english','Sentence Improvement','Idiomatic Improvements','idiom',6),

  ('ssc-english','Spellings','Vowel Patterns','vowels',1),
  ('ssc-english','Spellings','Silent Letters','silent',2),
  ('ssc-english','Spellings','Double Letter Words','double',3),
  ('ssc-english','Spellings','-able vs -ible','able-ible',4),
  ('ssc-english','Spellings','Foreign-Origin Words','foreign',5),
  ('ssc-english','Spellings','SSC Common PYQs','pyq',6),

  ('ssc-english','Spotting Errors','Tense Errors','tense',1),
  ('ssc-english','Spotting Errors','Article Errors','article',2),
  ('ssc-english','Spotting Errors','Preposition Errors','prep',3),
  ('ssc-english','Spotting Errors','Subject-Verb Agreement','sva',4),
  ('ssc-english','Spotting Errors','Pronoun-Antecedent','pronoun',5),
  ('ssc-english','Spotting Errors','Word Choice Errors','word-choice',6),

  ('ssc-english','Synonyms & Antonyms','Common Pairs','common',1),
  ('ssc-english','Synonyms & Antonyms','Latin/Greek Roots','roots',2),
  ('ssc-english','Synonyms & Antonyms','Shades of Meaning','shades',3),
  ('ssc-english','Synonyms & Antonyms','Formal Vocabulary','formal',4),
  ('ssc-english','Synonyms & Antonyms','Literary Vocabulary','literary',5),
  ('ssc-english','Synonyms & Antonyms','PYQ High-Frequency','pyq',6),

  -- SSC QUANT (15 chapters seeded here; 2 patched in 035: Heights & Distances, Mensuration (2D & 3D))
  ('ssc-quant','Number Systems','Divisibility Rules','divisibility',1),
  ('ssc-quant','Number Systems','LCM & HCF Applications','lcm-hcf',2),
  ('ssc-quant','Number Systems','Remainder Theorems','remainder',3),
  ('ssc-quant','Number Systems','Unit Digit & Cyclicity','unit-digit',4),
  ('ssc-quant','Number Systems','Number of Factors','factors',5),
  ('ssc-quant','Number Systems','Decimal & Fractions','decimals',6),

  ('ssc-quant','Simplification & Approximation','BODMAS','bodmas',1),
  ('ssc-quant','Simplification & Approximation','Surds & Indices','surds',2),
  ('ssc-quant','Simplification & Approximation','Square Roots','sqrt',3),
  ('ssc-quant','Simplification & Approximation','Approximation Techniques','approx',4),
  ('ssc-quant','Simplification & Approximation','Power & Exponent Tricks','power',5),
  ('ssc-quant','Simplification & Approximation','Vedic Shortcuts','vedic',6),

  ('ssc-quant','Percentages','Basic Conversions','basics',1),
  ('ssc-quant','Percentages','Successive Percentage','successive',2),
  ('ssc-quant','Percentages','Population Growth','population',3),
  ('ssc-quant','Percentages','Income & Expenditure','income',4),
  ('ssc-quant','Percentages','Exam Marks Problems','marks',5),
  ('ssc-quant','Percentages','PYQ Patterns','pyq',6),

  ('ssc-quant','Profit, Loss & Discount','Basic Profit/Loss','basics',1),
  ('ssc-quant','Profit, Loss & Discount','Successive Discounts','successive',2),
  ('ssc-quant','Profit, Loss & Discount','Marked Price Problems','mp',3),
  ('ssc-quant','Profit, Loss & Discount','Dishonest Dealer','dishonest',4),
  ('ssc-quant','Profit, Loss & Discount','Cost-Selling Tricks','cs-tricks',5),
  ('ssc-quant','Profit, Loss & Discount','Mixed P/L Problems','mixed',6),

  ('ssc-quant','Simple & Compound Interest','Simple Interest Basics','si',1),
  ('ssc-quant','Simple & Compound Interest','Compound Interest Basics','ci',2),
  ('ssc-quant','Simple & Compound Interest','SI vs CI Difference','si-ci',3),
  ('ssc-quant','Simple & Compound Interest','Time-Rate Problems','time-rate',4),
  ('ssc-quant','Simple & Compound Interest','Installments','installments',5),
  ('ssc-quant','Simple & Compound Interest','Quarterly/Half-Yearly','quarterly',6),

  ('ssc-quant','Ratio & Proportion','Basic Ratios','basics',1),
  ('ssc-quant','Ratio & Proportion','Compound Ratio','compound',2),
  ('ssc-quant','Ratio & Proportion','Partnership Problems','partnership',3),
  ('ssc-quant','Ratio & Proportion','Mean Proportional','mean',4),
  ('ssc-quant','Ratio & Proportion','Dividing in Ratio','divide',5),
  ('ssc-quant','Ratio & Proportion','Continued Ratio','continued',6),

  ('ssc-quant','Mixtures & Alligation','Two-Component Mixtures','two-comp',1),
  ('ssc-quant','Mixtures & Alligation','Alligation Rule','rule',2),
  ('ssc-quant','Mixtures & Alligation','Replacement Problems','replacement',3),
  ('ssc-quant','Mixtures & Alligation','Average Cost Mixing','avg-cost',4),
  ('ssc-quant','Mixtures & Alligation','Milk-Water Problems','milk-water',5),
  ('ssc-quant','Mixtures & Alligation','PYQ Patterns','pyq',6),

  ('ssc-quant','Time & Work','Individual Work Rate','individual',1),
  ('ssc-quant','Time & Work','Combined Work','combined',2),
  ('ssc-quant','Time & Work','Pipe & Cistern','pipes',3),
  ('ssc-quant','Time & Work','Wages & Efficiency','wages',4),
  ('ssc-quant','Time & Work','Alternate Day Work','alternate',5),
  ('ssc-quant','Time & Work','Negative Work','negative',6),

  ('ssc-quant','Time, Speed & Distance','Basic Formulas','basics',1),
  ('ssc-quant','Time, Speed & Distance','Relative Speed','relative',2),
  ('ssc-quant','Time, Speed & Distance','Train Problems','trains',3),
  ('ssc-quant','Time, Speed & Distance','Boat & Stream','boats',4),
  ('ssc-quant','Time, Speed & Distance','Circular Track','circular',5),
  ('ssc-quant','Time, Speed & Distance','Average Speed','avg-speed',6),

  ('ssc-quant','Trigonometry','Basic Identities','identities',1),
  ('ssc-quant','Trigonometry','Standard Angles','angles',2),
  ('ssc-quant','Trigonometry','Heights & Distances','heights',3),
  ('ssc-quant','Trigonometry','Complementary Angles','complementary',4),
  ('ssc-quant','Trigonometry','Maximum-Minimum Values','max-min',5),
  ('ssc-quant','Trigonometry','Trig Equations','equations',6),

  ('ssc-quant','Statistics & Probability','Mean, Median, Mode','central',1),
  ('ssc-quant','Statistics & Probability','Variance & Standard Deviation','variance',2),
  ('ssc-quant','Statistics & Probability','Probability Basics','prob-basics',3),
  ('ssc-quant','Statistics & Probability','Dice & Coin Problems','dice',4),
  ('ssc-quant','Statistics & Probability','Card Probability','cards',5),
  ('ssc-quant','Statistics & Probability','Conditional Probability','conditional',6),

  ('ssc-quant','Algebra','Linear Equations','linear',1),
  ('ssc-quant','Algebra','Quadratic Equations','quadratic',2),
  ('ssc-quant','Algebra','Algebraic Identities','identities',3),
  ('ssc-quant','Algebra','Factorization','factor',4),
  ('ssc-quant','Algebra','Polynomials','poly',5),
  ('ssc-quant','Algebra','Roots & Coefficients','roots',6),

  ('ssc-quant','Average','Basic Average','basics',1),
  ('ssc-quant','Average','Weighted Average','weighted',2),
  ('ssc-quant','Average','Age Problems','age',3),
  ('ssc-quant','Average','Cricket-Score Average','cricket',4),
  ('ssc-quant','Average','Replacement Effect','replace',5),
  ('ssc-quant','Average','Group Average','group',6),

  ('ssc-quant','Data Interpretation','Tables','tables',1),
  ('ssc-quant','Data Interpretation','Bar Graphs','bar',2),
  ('ssc-quant','Data Interpretation','Pie Charts','pie',3),
  ('ssc-quant','Data Interpretation','Line Graphs','line',4),
  ('ssc-quant','Data Interpretation','Mixed Charts','mixed',5),
  ('ssc-quant','Data Interpretation','Caselet DI','caselet',6),

  ('ssc-quant','Geometry','Triangles','triangles',1),
  ('ssc-quant','Geometry','Circles','circles',2),
  ('ssc-quant','Geometry','Quadrilaterals','quads',3),
  ('ssc-quant','Geometry','Lines & Angles','lines',4),
  ('ssc-quant','Geometry','Similar Triangles','similar',5),
  ('ssc-quant','Geometry','Coordinate Geometry','coord',6),

  ('ssc-quant','LCM & HCF','LCM Methods','lcm',1),
  ('ssc-quant','LCM & HCF','HCF Methods','hcf',2),
  ('ssc-quant','LCM & HCF','LCM x HCF Formula','formula',3),
  ('ssc-quant','LCM & HCF','Time-Based Problems','time',4),
  ('ssc-quant','LCM & HCF','Fraction LCM/HCF','fractions',5),
  ('ssc-quant','LCM & HCF','Real-World Applications','applications',6),

  -- SSC REASONING (15 chapters seeded here; 4 patched in 035: Analogies, Cause & Effect, Classification (Odd one out), Cube & Dice)
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Arithmetic Series','arithmetic',1),
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Geometric Series','geometric',2),
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Letter Series','letter',3),
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Mixed Number-Letter','mixed',4),
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Missing Term','missing',5),
  ('ssc-reasoning','Series (Number, Letter, Mixed)','Wrong Term','wrong',6),

  ('ssc-reasoning','Coding-Decoding','Letter Shifting','shift',1),
  ('ssc-reasoning','Coding-Decoding','Mathematical Coding','math',2),
  ('ssc-reasoning','Coding-Decoding','Substitution Coding','substitution',3),
  ('ssc-reasoning','Coding-Decoding','Symbol-Based','symbol',4),
  ('ssc-reasoning','Coding-Decoding','Mixed Word Coding','mixed',5),
  ('ssc-reasoning','Coding-Decoding','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Blood Relations','Family Tree','tree',1),
  ('ssc-reasoning','Blood Relations','Pointing Statements','pointing',2),
  ('ssc-reasoning','Blood Relations','Generation Logic','generation',3),
  ('ssc-reasoning','Blood Relations','Husband-Wife Riddles','husband-wife',4),
  ('ssc-reasoning','Blood Relations','Symbol-Based Relations','symbol',5),
  ('ssc-reasoning','Blood Relations','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Direction Sense','Basic Directions','basics',1),
  ('ssc-reasoning','Direction Sense','Shortest Distance','shortest',2),
  ('ssc-reasoning','Direction Sense','Turn-Based Movement','turn',3),
  ('ssc-reasoning','Direction Sense','Shadow Method','shadow',4),
  ('ssc-reasoning','Direction Sense','Compass Tricks','compass',5),
  ('ssc-reasoning','Direction Sense','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Syllogism','Three-Statement Syllogism','three',1),
  ('ssc-reasoning','Syllogism','All/Some/No Patterns','all-some-no',2),
  ('ssc-reasoning','Syllogism','Venn-Based Syllogism','venn',3),
  ('ssc-reasoning','Syllogism','Either-Or Conclusions','either-or',4),
  ('ssc-reasoning','Syllogism','Negative Statements','negative',5),
  ('ssc-reasoning','Syllogism','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Venn Diagrams','Two-Set Venn','two-set',1),
  ('ssc-reasoning','Venn Diagrams','Three-Set Venn','three-set',2),
  ('ssc-reasoning','Venn Diagrams','Intersection-Only','intersection',3),
  ('ssc-reasoning','Venn Diagrams','Complement Logic','complement',4),
  ('ssc-reasoning','Venn Diagrams','Word-to-Venn Mapping','mapping',5),
  ('ssc-reasoning','Venn Diagrams','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Seating Arrangement','Linear Arrangement','linear',1),
  ('ssc-reasoning','Seating Arrangement','Circular Arrangement','circular',2),
  ('ssc-reasoning','Seating Arrangement','Facing In/Out','facing',3),
  ('ssc-reasoning','Seating Arrangement','Double-Row Seating','double-row',4),
  ('ssc-reasoning','Seating Arrangement','Square/Rectangle Seating','square',5),
  ('ssc-reasoning','Seating Arrangement','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Ranking & Order','Position from Top','from-top',1),
  ('ssc-reasoning','Ranking & Order','Position from Bottom','from-bottom',2),
  ('ssc-reasoning','Ranking & Order','Both-Side Ranking','both-side',3),
  ('ssc-reasoning','Ranking & Order','Height/Age Order','height',4),
  ('ssc-reasoning','Ranking & Order','Mixed Order','mixed',5),
  ('ssc-reasoning','Ranking & Order','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Statement & Argument','Strong vs Weak','strong-weak',1),
  ('ssc-reasoning','Statement & Argument','Relevance Test','relevance',2),
  ('ssc-reasoning','Statement & Argument','Author-Position Logic','author',3),
  ('ssc-reasoning','Statement & Argument','Multiple Arguments','multiple',4),
  ('ssc-reasoning','Statement & Argument','Cause-Effect Logic','cause-effect',5),
  ('ssc-reasoning','Statement & Argument','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Statement & Assumption','Implicit Assumption','implicit',1),
  ('ssc-reasoning','Statement & Assumption','Explicit Assumption','explicit',2),
  ('ssc-reasoning','Statement & Assumption','Negative Logic','negative',3),
  ('ssc-reasoning','Statement & Assumption','Common Sense Filter','common-sense',4),
  ('ssc-reasoning','Statement & Assumption','PYQ Patterns','pyq',5),
  ('ssc-reasoning','Statement & Assumption','Multi-Statement','multi',6),

  ('ssc-reasoning','Statement & Conclusion','Direct Conclusion','direct',1),
  ('ssc-reasoning','Statement & Conclusion','Implied Conclusion','implied',2),
  ('ssc-reasoning','Statement & Conclusion','Either-Or Pattern','either-or',3),
  ('ssc-reasoning','Statement & Conclusion','Multi-Conclusion','multi',4),
  ('ssc-reasoning','Statement & Conclusion','Negative Conclusion','negative',5),
  ('ssc-reasoning','Statement & Conclusion','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Mirror & Water Images','Letter Mirror Image','letter-mirror',1),
  ('ssc-reasoning','Mirror & Water Images','Number Mirror Image','number-mirror',2),
  ('ssc-reasoning','Mirror & Water Images','Letter Water Image','letter-water',3),
  ('ssc-reasoning','Mirror & Water Images','Number Water Image','number-water',4),
  ('ssc-reasoning','Mirror & Water Images','Figure Mirror Image','fig-mirror',5),
  ('ssc-reasoning','Mirror & Water Images','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Paper Folding & Cutting','Single Fold','single',1),
  ('ssc-reasoning','Paper Folding & Cutting','Double Fold','double',2),
  ('ssc-reasoning','Paper Folding & Cutting','Triangular Fold','triangular',3),
  ('ssc-reasoning','Paper Folding & Cutting','Circular Cut','circular',4),
  ('ssc-reasoning','Paper Folding & Cutting','Punch-Hole Patterns','punch',5),
  ('ssc-reasoning','Paper Folding & Cutting','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Embedded Figures','Identify Hidden Figure','identify',1),
  ('ssc-reasoning','Embedded Figures','Match Original Outline','outline',2),
  ('ssc-reasoning','Embedded Figures','Multiple Embedded','multiple',3),
  ('ssc-reasoning','Embedded Figures','Rotation-Adjusted','rotation',4),
  ('ssc-reasoning','Embedded Figures','Overlap Logic','overlap',5),
  ('ssc-reasoning','Embedded Figures','PYQ Patterns','pyq',6),

  ('ssc-reasoning','Figure Counting','Triangle Counting','triangles',1),
  ('ssc-reasoning','Figure Counting','Square Counting','squares',2),
  ('ssc-reasoning','Figure Counting','Rectangle Counting','rectangles',3),
  ('ssc-reasoning','Figure Counting','Circle Counting','circles',4),
  ('ssc-reasoning','Figure Counting','Mixed Figures','mixed',5),
  ('ssc-reasoning','Figure Counting','PYQ Patterns','pyq',6),

  -- SSC GA (15 chapters seeded here; 1 patched in 035: World History)
  ('ssc-ga','Indian History','Ancient India','ancient',1),
  ('ssc-ga','Indian History','Medieval India','medieval',2),
  ('ssc-ga','Indian History','Modern India','modern',3),
  ('ssc-ga','Indian History','Freedom Struggle','freedom',4),
  ('ssc-ga','Indian History','Important Dates & Events','dates',5),
  ('ssc-ga','Indian History','National Leaders','leaders',6),

  ('ssc-ga','Indian Polity','Constitution Basics','constitution',1),
  ('ssc-ga','Indian Polity','Fundamental Rights & DPSP','rights',2),
  ('ssc-ga','Indian Polity','Parliamentary System','parliament',3),
  ('ssc-ga','Indian Polity','Judiciary & Courts','judiciary',4),
  ('ssc-ga','Indian Polity','States & Union Territories','states',5),
  ('ssc-ga','Indian Polity','Amendments','amendments',6),

  ('ssc-ga','Indian Geography','Physical Features','physical',1),
  ('ssc-ga','Indian Geography','Rivers & Drainage','rivers',2),
  ('ssc-ga','Indian Geography','Climate & Monsoon','climate',3),
  ('ssc-ga','Indian Geography','Agriculture & Soils','agriculture',4),
  ('ssc-ga','Indian Geography','Minerals & Industries','industries',5),
  ('ssc-ga','Indian Geography','National Parks','parks',6),

  ('ssc-ga','World Geography','Continents & Oceans','continents',1),
  ('ssc-ga','World Geography','Major Rivers of the World','rivers',2),
  ('ssc-ga','World Geography','Climate Zones','climate',3),
  ('ssc-ga','World Geography','Major Cities & Capitals','cities',4),
  ('ssc-ga','World Geography','Natural Wonders','wonders',5),
  ('ssc-ga','World Geography','World Boundaries & Lines','boundaries',6),

  ('ssc-ga','Indian Economy','GDP & National Income','gdp',1),
  ('ssc-ga','Indian Economy','Banking & RBI','banking',2),
  ('ssc-ga','Indian Economy','Budget & Taxation','budget',3),
  ('ssc-ga','Indian Economy','Planning & NITI Aayog','planning',4),
  ('ssc-ga','Indian Economy','Five-Year Plans','five-year',5),
  ('ssc-ga','Indian Economy','Economic Reforms','reforms',6),

  ('ssc-ga','General Science: Physics','Mechanics Basics','mechanics',1),
  ('ssc-ga','General Science: Physics','Optics & Light','optics',2),
  ('ssc-ga','General Science: Physics','Electricity & Magnetism','electric',3),
  ('ssc-ga','General Science: Physics','Heat & Thermodynamics','heat',4),
  ('ssc-ga','General Science: Physics','Sound Waves','sound',5),
  ('ssc-ga','General Science: Physics','Modern Physics','modern',6),

  ('ssc-ga','General Science: Chemistry','Atomic Structure','atomic',1),
  ('ssc-ga','General Science: Chemistry','Periodic Table','periodic',2),
  ('ssc-ga','General Science: Chemistry','Acids, Bases & Salts','acids',3),
  ('ssc-ga','General Science: Chemistry','Organic Chemistry Basics','organic',4),
  ('ssc-ga','General Science: Chemistry','Metals & Non-Metals','metals',5),
  ('ssc-ga','General Science: Chemistry','Everyday Chemistry','everyday',6),

  ('ssc-ga','General Science: Biology','Human Body Systems','human-body',1),
  ('ssc-ga','General Science: Biology','Plant Biology','plants',2),
  ('ssc-ga','General Science: Biology','Genetics & Heredity','genetics',3),
  ('ssc-ga','General Science: Biology','Microbiology','microbio',4),
  ('ssc-ga','General Science: Biology','Diseases & Health','health',5),
  ('ssc-ga','General Science: Biology','Ecology & Environment','ecology',6),

  ('ssc-ga','Current Affairs','National News','national',1),
  ('ssc-ga','Current Affairs','International News','international',2),
  ('ssc-ga','Current Affairs','Economy News','economy',3),
  ('ssc-ga','Current Affairs','Sports News','sports',4),
  ('ssc-ga','Current Affairs','Science & Tech','sci-tech',5),
  ('ssc-ga','Current Affairs','Government Schemes','schemes',6),

  ('ssc-ga','Static GK','Important Days & Themes','days',1),
  ('ssc-ga','Static GK','National Symbols','symbols',2),
  ('ssc-ga','Static GK','Dances & Music of India','dances',3),
  ('ssc-ga','Static GK','Important Organisations','orgs',4),
  ('ssc-ga','Static GK','Capitals & Currencies','capitals',5),
  ('ssc-ga','Static GK','Famous Personalities','people',6),

  ('ssc-ga','Computer Awareness','Computer Fundamentals','fundamentals',1),
  ('ssc-ga','Computer Awareness','Operating Systems','os',2),
  ('ssc-ga','Computer Awareness','MS Office Basics','office',3),
  ('ssc-ga','Computer Awareness','Internet & Email','internet',4),
  ('ssc-ga','Computer Awareness','Cyber Security','security',5),
  ('ssc-ga','Computer Awareness','Computer Abbreviations','abbreviations',6),

  ('ssc-ga','Books & Authors','Indian Authors','indian',1),
  ('ssc-ga','Books & Authors','International Authors','international',2),
  ('ssc-ga','Books & Authors','Autobiographies','auto',3),
  ('ssc-ga','Books & Authors','Recent Releases','recent',4),
  ('ssc-ga','Books & Authors','Award-Winning Books','awards',5),
  ('ssc-ga','Books & Authors','Indian Mythology Texts','mythology',6),

  ('ssc-ga','Awards & Honours','Bharat Ratna & Padma','bharat-ratna',1),
  ('ssc-ga','Awards & Honours','Nobel Prizes','nobel',2),
  ('ssc-ga','Awards & Honours','Magsaysay & Jnanpith','magsaysay',3),
  ('ssc-ga','Awards & Honours','Sports Awards','sports',4),
  ('ssc-ga','Awards & Honours','Film Awards','film',5),
  ('ssc-ga','Awards & Honours','Recent Awards','recent',6),

  ('ssc-ga','Important Days','International Days (Jan-Jun)','intl-h1',1),
  ('ssc-ga','Important Days','International Days (Jul-Dec)','intl-h2',2),
  ('ssc-ga','Important Days','National Days','national',3),
  ('ssc-ga','Important Days','Health-Themed Days','health',4),
  ('ssc-ga','Important Days','Environment-Themed Days','environment',5),
  ('ssc-ga','Important Days','UN Observances','un',6),

  ('ssc-ga','Sports','Cricket Records & Cups','cricket',1),
  ('ssc-ga','Sports','Olympics & Asian Games','olympics',2),
  ('ssc-ga','Sports','Football World Cup','football',3),
  ('ssc-ga','Sports','Tennis Grand Slams','tennis',4),
  ('ssc-ga','Sports','Indigenous Indian Sports','indigenous',5),
  ('ssc-ga','Sports','Sports Awards & Personalities','personalities',6)
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, r.topic_name, r.topic_slug,
       format('Practice questions on %s within %s.', r.topic_name, c.name),
       r.ord
from raw r
join public.chapters c on c.name = r.chapter_name
join public.subjects s on s.id = c.subject_id and s.id = r.subject_id
on conflict (chapter_id, slug) do update set
  name        = excluded.name,
  description = excluded.description,
  order_index = excluded.order_index;
