-- Replace the five-chapter starter maps for the two live RO/ARO routes with
-- fuller preparation maps. This is additive: no learner attempts, answers or
-- progress records are removed. The first five existing chapters remain useful
-- foundations; this migration supplies the missing syllabus-level coverage.
--
-- The exact paper mix, eligibility and skill-test requirements can change by
-- notification. These maps cover the written-preparation route only.

with raw(subject_key, name, slug, ord) as (values
  -- General Studies: history, geography, polity, economy, science, UP and CA
  ('gs', 'Ancient India & Cultural Foundations', 'ancient-india-cultural-foundations', 6),
  ('gs', 'Medieval India & Regional History', 'medieval-india-regional-history', 7),
  ('gs', 'Modern India & Freedom Struggle', 'modern-india-freedom-struggle', 8),
  ('gs', 'Indian Geography', 'indian-geography', 9),
  ('gs', 'World Geography & Environment', 'world-geography-environment', 10),
  ('gs', 'Indian Economy & Public Finance', 'indian-economy-public-finance', 11),
  ('gs', 'General Science & Technology', 'general-science-technology', 12),
  ('gs', 'Uttar Pradesh: History, Geography & Culture', 'up-history-geography-culture', 13),
  ('gs', 'Uttar Pradesh: Economy, Administration & Schemes', 'up-economy-administration-schemes', 14),
  ('gs', 'Current Affairs: India, Uttar Pradesh & World', 'current-affairs-india-up-world', 15),
  -- Hindi: grammar, vocabulary, comprehension and drafting
  ('hindi', 'वर्ण-विचार, शब्द-रचना और वर्तनी', 'varna-vichar-shabd-rachna-vartani', 6),
  ('hindi', 'संज्ञा, सर्वनाम, विशेषण और क्रिया', 'parts-of-speech', 7),
  ('hindi', 'काल, वाच्य, कारक और वाक्य-रचना', 'tense-voice-case-sentence', 8),
  ('hindi', 'पर्यायवाची, विलोम और शब्द-भेद', 'synonyms-antonyms-word-types', 9),
  ('hindi', 'तत्सम-तद्भव, देशज और विदेशी शब्द', 'tatsam-tadbhav-deshaj-videshi', 10),
  ('hindi', 'मुहावरे, लोकोक्तियाँ और एक-शब्द', 'idioms-proverbs-one-word', 11),
  ('hindi', 'अपठित गद्यांश और भाव-बोध', 'unseen-passage-comprehension', 12),
  ('hindi', 'संक्षेपण, शीर्षक और सार-लेखन', 'precis-title-summary', 13),
  ('hindi', 'पत्र, टिप्पणी और कार्यालयी प्रारूपण', 'official-letter-note-drafting', 14),
  ('hindi', 'हिंदी संपादन और त्रुटि-सुधार', 'hindi-editing-error-correction', 15),
  -- Computer: an office-work preparation tree instead of a four-card overview
  ('computer', 'Computer Generations & System Architecture', 'computer-generations-system-architecture', 6),
  ('computer', 'Data Representation & Number Systems', 'data-representation-number-systems', 7),
  ('computer', 'Operating Systems, Files & Utilities', 'operating-systems-files-utilities', 8),
  ('computer', 'Networks, Internet & E-mail', 'networks-internet-email', 9),
  ('computer', 'MS Word: Documents & Formatting', 'ms-word-documents-formatting', 10),
  ('computer', 'MS Excel: Formulas, Tables & Charts', 'ms-excel-formulas-tables-charts', 11),
  ('computer', 'MS PowerPoint & Presentations', 'ms-powerpoint-presentations', 12),
  ('computer', 'Databases & Data Management', 'databases-data-management', 13),
  ('computer', 'Cyber Security & Digital Safety', 'cyber-security-digital-safety', 14),
  ('computer', 'Office Shortcuts & Practical Commands', 'office-shortcuts-practical-commands', 15),
  -- Reasoning: separate scoring families rather than one generic conditions card
  ('reasoning', 'Coding-Decoding & Alphabet Logic', 'coding-decoding-alphabet-logic', 6),
  ('reasoning', 'Syllogism, Venn Diagrams & Set Logic', 'syllogism-venn-set-logic', 7),
  ('reasoning', 'Seating Arrangement & Puzzles', 'seating-arrangement-puzzles', 8),
  ('reasoning', 'Calendar, Clock & Time Logic', 'calendar-clock-time-logic', 9),
  ('reasoning', 'Mathematical Operations & Missing Values', 'mathematical-operations-missing-values', 10),
  ('reasoning', 'Decision Making & Statement Logic', 'decision-making-statement-logic', 11),
  ('reasoning', 'Non-verbal Reasoning', 'non-verbal-reasoning', 12),
  ('reasoning', 'Data Sufficiency & Data Interpretation', 'data-sufficiency-data-interpretation', 13),
  ('reasoning', 'Order, Ranking & Comparison', 'order-ranking-comparison', 14),
  ('reasoning', 'Mixed Reasoning Practice', 'mixed-reasoning-practice', 15)
), targets as (
  select 'uppsc-ro-' || subject_key as subject_id, name, slug, ord from raw
  union all
  select 'up-secretariat-' || subject_key as subject_id, name, slug, ord from raw
)
insert into public.chapters (subject_id, name, slug, order_index)
select subject_id, name, slug, ord from targets
on conflict (subject_id, slug) do update set name = excluded.name, order_index = excluded.order_index;

-- Detailed, reusable written-preparation modules. Each is attached to both
-- routes but lives under its own chapter IDs, so learner evidence never mixes.
with raw(subject_key, chapter_slug, name, slug, ord) as (values
  ('gs','ancient-india-cultural-foundations','Indus Valley & Vedic Age','indus-valley-vedic-age',1),
  ('gs','ancient-india-cultural-foundations','Mahajanapadas, Buddhism & Jainism','mahajanapadas-buddhism-jainism',2),
  ('gs','ancient-india-cultural-foundations','Maurya & Gupta Periods','maurya-gupta-periods',3),
  ('gs','ancient-india-cultural-foundations','Classical Art, Literature & Religion','classical-art-literature-religion',4),
  ('gs','medieval-india-regional-history','Delhi Sultanate','delhi-sultanate',1),
  ('gs','medieval-india-regional-history','Mughal Administration & Culture','mughal-administration-culture',2),
  ('gs','medieval-india-regional-history','Bhakti and Sufi Movements','bhakti-sufi-movements',3),
  ('gs','medieval-india-regional-history','Regional Kingdoms & UP Links','regional-kingdoms-up-links',4),
  ('gs','modern-india-freedom-struggle','British Expansion & Administrative Acts','british-expansion-administrative-acts',1),
  ('gs','modern-india-freedom-struggle','Social and Religious Reform','social-religious-reform',2),
  ('gs','modern-india-freedom-struggle','National Movement: 1885 to 1919','national-movement-1885-1919',3),
  ('gs','modern-india-freedom-struggle','Gandhian Phase & Constitutional Developments','gandhian-phase-constitutional-developments',4),
  ('gs','indian-geography','Physiography, Rivers & Soils','physiography-rivers-soils',1),
  ('gs','indian-geography','Climate, Monsoon & Natural Vegetation','climate-monsoon-natural-vegetation',2),
  ('gs','indian-geography','Agriculture, Minerals & Industries','agriculture-minerals-industries',3),
  ('gs','indian-geography','Population, Transport & Mapping','population-transport-mapping',4),
  ('gs','world-geography-environment','Earth Structure, Latitude & Longitude','earth-structure-latitude-longitude',1),
  ('gs','world-geography-environment','Landforms, Oceans & Climate Systems','landforms-oceans-climate-systems',2),
  ('gs','world-geography-environment','Ecosystems, Biodiversity & Conservation','ecosystems-biodiversity-conservation',3),
  ('gs','world-geography-environment','Pollution, Climate Change & Agreements','pollution-climate-change-agreements',4),
  ('gs','indian-economy-public-finance','National Income, Inflation & Employment','national-income-inflation-employment',1),
  ('gs','indian-economy-public-finance','Banking, RBI & Monetary Policy','banking-rbi-monetary-policy',2),
  ('gs','indian-economy-public-finance','Budget, Taxation & Public Finance','budget-taxation-public-finance',3),
  ('gs','indian-economy-public-finance','Planning, Sectors & External Economy','planning-sectors-external-economy',4),
  ('gs','general-science-technology','Physics in Everyday Life','physics-everyday-life',1),
  ('gs','general-science-technology','Chemistry in Everyday Life','chemistry-everyday-life',2),
  ('gs','general-science-technology','Biology, Health & Human Body','biology-health-human-body',3),
  ('gs','general-science-technology','Space, IT & Emerging Technology','space-it-emerging-technology',4),
  ('gs','up-history-geography-culture','UP Historical Sites & Personalities','up-historical-sites-personalities',1),
  ('gs','up-history-geography-culture','UP Physical Geography & Rivers','up-physical-geography-rivers',2),
  ('gs','up-history-geography-culture','UP Art, Culture, Fairs & Festivals','up-art-culture-fairs-festivals',3),
  ('gs','up-history-geography-culture','UP Districts, Cities & Institutions','up-districts-cities-institutions',4),
  ('gs','up-economy-administration-schemes','UP Government & Administrative Structure','up-government-administrative-structure',1),
  ('gs','up-economy-administration-schemes','UP Agriculture, Industry & Infrastructure','up-agriculture-industry-infrastructure',2),
  ('gs','up-economy-administration-schemes','UP Social Sector & Flagship Schemes','up-social-sector-flagship-schemes',3),
  ('gs','up-economy-administration-schemes','UP Budget, Data & Development Indicators','up-budget-data-development-indicators',4),
  ('gs','current-affairs-india-up-world','National Governance & Schemes','national-governance-schemes',1),
  ('gs','current-affairs-india-up-world','UP Current Affairs','up-current-affairs',2),
  ('gs','current-affairs-india-up-world','International Organisations & Events','international-organisations-events',3),
  ('gs','current-affairs-india-up-world','Reports, Indices, Awards & Appointments','reports-indices-awards-appointments',4),
  ('hindi','varna-vichar-shabd-rachna-vartani','वर्ण, स्वर और व्यंजन','varn-swar-vyanjan',1),
  ('hindi','varna-vichar-shabd-rachna-vartani','शब्द-निर्माण और वर्तनी','shabd-nirman-vartani',2),
  ('hindi','varna-vichar-shabd-rachna-vartani','संधि-विच्छेद और समास-विग्रह','sandhi-vicched-samas-vigrah',3),
  ('hindi','varna-vichar-shabd-rachna-vartani','उपसर्ग और प्रत्यय प्रयोग','upsarg-pratyay-prayog',4),
  ('hindi','parts-of-speech','संज्ञा और सर्वनाम','sangya-sarvanam',1),
  ('hindi','parts-of-speech','विशेषण और क्रिया','visheshan-kriya',2),
  ('hindi','parts-of-speech','क्रिया-विशेषण, अव्यय और संबंधबोधक','kriya-visheshan-avyay-sambandhbodhak',3),
  ('hindi','parts-of-speech','पद-परिचय','pad-parichay',4),
  ('hindi','tense-voice-case-sentence','काल और वाच्य','kaal-vaachya',1),
  ('hindi','tense-voice-case-sentence','कारक और विभक्ति','karak-vibhakti',2),
  ('hindi','tense-voice-case-sentence','वाक्य के भेद और रूपांतरण','vakya-bhed-roopantaran',3),
  ('hindi','tense-voice-case-sentence','वाक्य क्रम और सामंजस्य','vakya-kram-samanjasya',4),
  ('hindi','synonyms-antonyms-word-types','पर्यायवाची शब्द','paryayvachi-shabd',1),
  ('hindi','synonyms-antonyms-word-types','विलोम शब्द','vilom-shabd',2),
  ('hindi','synonyms-antonyms-word-types','श्रुतिसम भिन्नार्थक शब्द','shruti-sam-bhinnarthak',3),
  ('hindi','synonyms-antonyms-word-types','शब्द-युग्म और सही प्रयोग','shabd-yugm-sahi-prayog',4),
  ('hindi','tatsam-tadbhav-deshaj-videshi','तत्सम और तद्भव','tatsam-tadbhav',1),
  ('hindi','tatsam-tadbhav-deshaj-videshi','देशज और विदेशी शब्द','deshaj-videshi-shabd',2),
  ('hindi','tatsam-tadbhav-deshaj-videshi','अनेक शब्दों के लिए एक शब्द','anek-shabdon-ke-liye-ek',3),
  ('hindi','tatsam-tadbhav-deshaj-videshi','सही शब्द-चयन','sahi-shabd-chayan',4),
  ('hindi','idioms-proverbs-one-word','मुहावरे','muhavare',1),
  ('hindi','idioms-proverbs-one-word','लोकोक्तियाँ','lokoktiyan',2),
  ('hindi','idioms-proverbs-one-word','वाक्यांश के लिए एक शब्द','vakyansh-ek-shabd',3),
  ('hindi','idioms-proverbs-one-word','प्रयोग आधारित अभ्यास','prayog-aadharit-abhyas',4),
  ('hindi','unseen-passage-comprehension','मुख्य विचार और उद्देश्य','mukhya-vichar-uddeshya',1),
  ('hindi','unseen-passage-comprehension','तथ्य, अनुमान और निष्कर्ष','tathya-anuman-nishkarsh',2),
  ('hindi','unseen-passage-comprehension','शब्दार्थ और संदर्भ','shabdarth-sandarbh',3),
  ('hindi','unseen-passage-comprehension','गद्यांश आधारित प्रश्न','gadyansh-aadharit-prashn',4),
  ('hindi','precis-title-summary','संक्षेपण की विधि','sankshepan-vidhi',1),
  ('hindi','precis-title-summary','शीर्षक चयन','shirshak-chayan',2),
  ('hindi','precis-title-summary','सार-लेखन','saar-lekhan',3),
  ('hindi','precis-title-summary','अर्थ बचाते हुए संक्षिप्त करना','arth-bachate-hue-sankshipt',4),
  ('hindi','official-letter-note-drafting','औपचारिक पत्र','aupcharik-patra',1),
  ('hindi','official-letter-note-drafting','नोट, ज्ञापन और आदेश','note-gyapan-aadesh',2),
  ('hindi','official-letter-note-drafting','अनुच्छेद और मसौदा लेखन','anuched-masouda-lekhan',3),
  ('hindi','official-letter-note-drafting','स्पष्टता, क्रम और शिष्ट भाषा','spashtata-kram-shisht-bhasha',4),
  ('hindi','hindi-editing-error-correction','वर्तनी और विराम-चिह्न','vartani-viram-chinh',1),
  ('hindi','hindi-editing-error-correction','लिंग, वचन और कारक त्रुटि','ling-vachan-karak-truti',2),
  ('hindi','hindi-editing-error-correction','काल और वाच्य त्रुटि','kaal-vaachya-truti',3),
  ('hindi','hindi-editing-error-correction','अशुद्ध वाक्य सुधार','ashuddh-vakya-sudhar',4),
  ('computer','computer-generations-system-architecture','Computer Generations','computer-generations',1),
  ('computer','computer-generations-system-architecture','CPU, ALU and Control Unit','cpu-alu-control-unit',2),
  ('computer','computer-generations-system-architecture','Input and Output Devices','input-output-devices',3),
  ('computer','computer-generations-system-architecture','Primary and Secondary Memory','primary-secondary-memory',4),
  ('computer','data-representation-number-systems','Bits, Bytes and Storage Units','bits-bytes-storage-units',1),
  ('computer','data-representation-number-systems','Binary, Decimal and Hexadecimal','binary-decimal-hexadecimal',2),
  ('computer','data-representation-number-systems','Character Encoding','character-encoding',3),
  ('computer','data-representation-number-systems','Data Types and Logical Values','data-types-logical-values',4),
  ('computer','operating-systems-files-utilities','Operating System Functions','operating-system-functions',1),
  ('computer','operating-systems-files-utilities','Files, Folders and Extensions','files-folders-extensions-deep',2),
  ('computer','operating-systems-files-utilities','Booting and Utility Software','booting-utility-software',3),
  ('computer','operating-systems-files-utilities','Compression, Backup and Recovery','compression-backup-recovery',4),
  ('computer','networks-internet-email','LAN, WAN and Network Devices','lan-wan-network-devices',1),
  ('computer','networks-internet-email','Browsers, Search and URLs','browsers-search-urls',2),
  ('computer','networks-internet-email','E-mail, Attachments and Protocols','email-attachments-protocols',3),
  ('computer','networks-internet-email','Cloud Services and Collaboration','cloud-services-collaboration',4),
  ('computer','ms-word-documents-formatting','Word Interface and File Operations','word-interface-file-operations',1),
  ('computer','ms-word-documents-formatting','Text, Paragraph and Page Formatting','text-paragraph-page-formatting',2),
  ('computer','ms-word-documents-formatting','Tables, Headers and Mail Merge','tables-headers-mail-merge',3),
  ('computer','ms-word-documents-formatting','Proofing, Print and PDF','proofing-print-pdf',4),
  ('computer','ms-excel-formulas-tables-charts','Workbook, Cells and References','workbook-cells-references',1),
  ('computer','ms-excel-formulas-tables-charts','Formulas and Functions','formulas-functions',2),
  ('computer','ms-excel-formulas-tables-charts','Sorting, Filtering and Tables','sorting-filtering-tables',3),
  ('computer','ms-excel-formulas-tables-charts','Charts and Data Presentation','charts-data-presentation',4),
  ('computer','ms-powerpoint-presentations','Slides, Themes and Layouts','slides-themes-layouts',1),
  ('computer','ms-powerpoint-presentations','Text, Images and SmartArt','text-images-smartart',2),
  ('computer','ms-powerpoint-presentations','Transitions and Animation','transitions-animation',3),
  ('computer','ms-powerpoint-presentations','Slide Show and Export','slide-show-export',4),
  ('computer','databases-data-management','Database, Table and Record','database-table-record',1),
  ('computer','databases-data-management','Fields, Keys and Relationships','fields-keys-relationships',2),
  ('computer','databases-data-management','Queries, Forms and Reports','queries-forms-reports',3),
  ('computer','databases-data-management','Data Validation Basics','data-validation-basics',4),
  ('computer','cyber-security-digital-safety','Malware, Antivirus and Firewall','malware-antivirus-firewall',1),
  ('computer','cyber-security-digital-safety','Passwords, MFA and Phishing','passwords-mfa-phishing',2),
  ('computer','cyber-security-digital-safety','Safe Browsing and Social Engineering','safe-browsing-social-engineering',3),
  ('computer','cyber-security-digital-safety','Privacy, Digital Footprint and Backups','privacy-digital-footprint-backups',4),
  ('computer','office-shortcuts-practical-commands','Common Keyboard Shortcuts','common-keyboard-shortcuts-deep',1),
  ('computer','office-shortcuts-practical-commands','Windows and File Commands','windows-file-commands',2),
  ('computer','office-shortcuts-practical-commands','Browser and E-mail Commands','browser-email-commands',3),
  ('computer','office-shortcuts-practical-commands','Office Workflow Scenarios','office-workflow-scenarios',4),
  ('reasoning','coding-decoding-alphabet-logic','Letter and Number Coding','letter-number-coding',1),
  ('reasoning','coding-decoding-alphabet-logic','Word and Symbol Coding','word-symbol-coding',2),
  ('reasoning','coding-decoding-alphabet-logic','Alphabet Positions and Series','alphabet-positions-series',3),
  ('reasoning','coding-decoding-alphabet-logic','Pattern and Rule Identification','pattern-rule-identification',4),
  ('reasoning','syllogism-venn-set-logic','Syllogism Statements','syllogism-statements',1),
  ('reasoning','syllogism-venn-set-logic','Venn Diagrams','venn-diagrams',2),
  ('reasoning','syllogism-venn-set-logic','Some, All and None Logic','some-all-none-logic',3),
  ('reasoning','syllogism-venn-set-logic','Conclusion Testing','conclusion-testing',4),
  ('reasoning','seating-arrangement-puzzles','Linear Arrangement','linear-arrangement',1),
  ('reasoning','seating-arrangement-puzzles','Circular Arrangement','circular-arrangement',2),
  ('reasoning','seating-arrangement-puzzles','Floor and Box Puzzles','floor-box-puzzles',3),
  ('reasoning','seating-arrangement-puzzles','Condition Grid Method','condition-grid-method',4),
  ('reasoning','calendar-clock-time-logic','Day and Date Calculation','day-date-calculation',1),
  ('reasoning','calendar-clock-time-logic','Calendar Patterns','calendar-patterns',2),
  ('reasoning','calendar-clock-time-logic','Clock Angles','clock-angles',3),
  ('reasoning','calendar-clock-time-logic','Time Sequence Logic','time-sequence-logic',4),
  ('reasoning','mathematical-operations-missing-values','Operator Substitution','operator-substitution',1),
  ('reasoning','mathematical-operations-missing-values','Missing Number Patterns','missing-number-patterns',2),
  ('reasoning','mathematical-operations-missing-values','Equation Balance','equation-balance',3),
  ('reasoning','mathematical-operations-missing-values','Rule Check Before Calculation','rule-check-before-calculation',4),
  ('reasoning','decision-making-statement-logic','Statement and Assumption','statement-assumption',1),
  ('reasoning','decision-making-statement-logic','Statement and Argument','statement-argument',2),
  ('reasoning','decision-making-statement-logic','Cause and Effect','cause-effect',3),
  ('reasoning','decision-making-statement-logic','Course of Action','course-of-action',4),
  ('reasoning','non-verbal-reasoning','Figure Analogy and Classification','figure-analogy-classification',1),
  ('reasoning','non-verbal-reasoning','Mirror and Water Images','mirror-water-images',2),
  ('reasoning','non-verbal-reasoning','Paper Folding and Cutting','paper-folding-cutting',3),
  ('reasoning','non-verbal-reasoning','Embedded Figures and Completion','embedded-figures-completion',4),
  ('reasoning','data-sufficiency-data-interpretation','Data Sufficiency Questions','data-sufficiency-questions',1),
  ('reasoning','data-sufficiency-data-interpretation','Tables and Bar Graphs','tables-bar-graphs',2),
  ('reasoning','data-sufficiency-data-interpretation','Pie Charts and Line Graphs','pie-charts-line-graphs',3),
  ('reasoning','data-sufficiency-data-interpretation','Comparison and Estimation','comparison-estimation',4),
  ('reasoning','order-ranking-comparison','Rank from Both Ends','rank-from-both-ends',1),
  ('reasoning','order-ranking-comparison','Age and Height Comparison','age-height-comparison',2),
  ('reasoning','order-ranking-comparison','Order of Events','order-of-events',3),
  ('reasoning','order-ranking-comparison','Relative Position','relative-position',4),
  ('reasoning','mixed-reasoning-practice','Multi-concept Question Selection','multi-concept-question-selection',1),
  ('reasoning','mixed-reasoning-practice','Read Conditions Before Options','read-conditions-before-options',2),
  ('reasoning','mixed-reasoning-practice','Eliminate Contradictions','eliminate-contradictions-deep',3),
  ('reasoning','mixed-reasoning-practice','Timed Mixed Sets','timed-mixed-sets',4)
), topic_targets as (
  select 'uppsc-ro-' || subject_key as subject_id, chapter_slug, name, slug, ord from raw
  union all
  select 'up-secretariat-' || subject_key as subject_id, chapter_slug, name, slug, ord from raw
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, t.name, t.slug,
       format('Build %s with focused practice, a concise revision note and a later retest.', t.name),
       t.ord
from topic_targets t
join public.chapters c on c.subject_id = t.subject_id and c.slug = t.chapter_slug
on conflict (chapter_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  order_index = excluded.order_index;
