-- Deepen only the UP Samiksha Adhikari / Sahayak Samiksha Adhikari route.
--
-- The earlier shared RO/ARO foundation used four leaves under many chapters.
-- That is enough for a starter map, but not for a student who needs to learn
-- a broad unit step-by-step. This migration is additive and preserves every
-- existing chapter, topic URL and learner-progress record.
--
-- The map is written-preparation content, not a claim about a future
-- notification's exact paper pattern, vacancy, typing test or eligibility.

with raw(subject_id, chapter_slug, name, slug, ord) as (values
  -- GENERAL STUDIES: give each large syllabus area a usable second layer.
  ('up-secretariat-gs','polity-governance','Preamble, Citizenship and Constitutional Values','preamble-citizenship-values',5),
  ('up-secretariat-gs','polity-governance','Union Executive: President, Prime Minister and Council','union-executive',6),
  ('up-secretariat-gs','polity-governance','Judiciary, Emergency Provisions and Constitutional Bodies','judiciary-emergency-bodies',7),
  ('up-secretariat-gs','polity-governance','Panchayats, Municipalities and Grassroots Governance','local-government-deep',8),
  ('up-secretariat-gs','history-culture','Indus Valley, Vedic Age and Early States','early-india-foundations',5),
  ('up-secretariat-gs','history-culture','Delhi Sultanate, Mughals and Administration','sultanate-mughal-administration',6),
  ('up-secretariat-gs','history-culture','Revolt of 1857, Congress and Freedom Movement','freedom-movement-core',7),
  ('up-secretariat-gs','history-culture','Indian Art, Architecture, Dances and Literature','indian-culture-core',8),
  ('up-secretariat-gs','geography-economy-science','Indian Landforms, Rivers and Climate','india-landforms-rivers-climate',5),
  ('up-secretariat-gs','geography-economy-science','Agriculture, Minerals, Energy and Industry','india-resources-industry',6),
  ('up-secretariat-gs','geography-economy-science','Inflation, Banking, Budget and Taxation','economy-core-concepts',7),
  ('up-secretariat-gs','geography-economy-science','Physics, Chemistry and Biology in Daily Life','science-core-concepts',8),
  ('up-secretariat-gs','uttar-pradesh-special','UP Location, Districts, Divisions and Boundaries','up-map-districts-divisions',5),
  ('up-secretariat-gs','uttar-pradesh-special','UP Rivers, Soils, Agriculture and Irrigation','up-rivers-agriculture-irrigation',6),
  ('up-secretariat-gs','uttar-pradesh-special','UP Art, Culture, Fairs and Important Places','up-culture-places-deep',7),
  ('up-secretariat-gs','uttar-pradesh-special','UP Administration, Schemes and Development','up-administration-development',8),
  ('up-secretariat-gs','current-affairs-method','Daily News: What Is Actually Worth Noting','daily-news-selection',5),
  ('up-secretariat-gs','current-affairs-method','Issue Notes: Context, Facts and Static Link','issue-note-method',6),
  ('up-secretariat-gs','current-affairs-method','Monthly Revision and One-Page Consolidation','monthly-current-affairs-revision',7),
  ('up-secretariat-gs','current-affairs-method','Current Affairs MCQ Elimination and Retention','current-affairs-mcq-retention',8),
  ('up-secretariat-gs','ancient-india-cultural-foundations','Harappan Civilization: Sites, Town Planning and Artefacts','harappan-civilization',5),
  ('up-secretariat-gs','ancient-india-cultural-foundations','Vedic Society, Literature and Political Institutions','vedic-society-literature',6),
  ('up-secretariat-gs','ancient-india-cultural-foundations','Mauryan Empire, Ashoka and Administration','mauryan-ashoka-administration',7),
  ('up-secretariat-gs','ancient-india-cultural-foundations','Gupta Age, Science, Art and Literature','gupta-age-culture',8),
  ('up-secretariat-gs','medieval-india-regional-history','Delhi Sultanate: Dynasties and Administration','delhi-sultanate-deep',5),
  ('up-secretariat-gs','medieval-india-regional-history','Mughal Rulers, Mansabdari and Culture','mughal-rulers-mansabdari',6),
  ('up-secretariat-gs','medieval-india-regional-history','Bhakti and Sufi Saints, Ideas and Literature','bhakti-sufi-deep',7),
  ('up-secretariat-gs','medieval-india-regional-history','Regional Kingdoms and Uttar Pradesh Connections','regional-kingdoms-up-deep',8),
  ('up-secretariat-gs','modern-india-freedom-struggle','Company Rule, Acts and British Expansion','company-rule-acts',5),
  ('up-secretariat-gs','modern-india-freedom-struggle','Reform Movements and Social Change','reform-movements-deep',6),
  ('up-secretariat-gs','modern-india-freedom-struggle','Congress Sessions, Moderates and Extremists','congress-moderates-extremists',7),
  ('up-secretariat-gs','modern-india-freedom-struggle','Gandhian Movements, INA and Independence','gandhian-ina-independence',8),
  ('up-secretariat-gs','indian-geography','Himalayas, Northern Plains and Peninsular Plateau','india-physiographic-divisions-deep',5),
  ('up-secretariat-gs','indian-geography','Himalayan and Peninsular River Systems','india-river-systems-deep',6),
  ('up-secretariat-gs','indian-geography','Monsoon, Seasons, Soils and Natural Vegetation','india-climate-soils-vegetation',7),
  ('up-secretariat-gs','indian-geography','States, Cities, Transport Corridors and Map Practice','india-map-practice-deep',8),
  ('up-secretariat-gs','world-geography-environment','Earth Motions, Latitude, Longitude and Time','earth-coordinates-time',5),
  ('up-secretariat-gs','world-geography-environment','Mountains, Plateaus, Deserts and Major Rivers','world-landforms-rivers',6),
  ('up-secretariat-gs','world-geography-environment','Oceans, Winds, Climate Regions and Currents','oceans-winds-climate',7),
  ('up-secretariat-gs','world-geography-environment','Biodiversity Hotspots, Protected Areas and Treaties','biodiversity-treaties',8),
  ('up-secretariat-gs','indian-economy-public-finance','GDP, National Income, Poverty and Employment','gdp-income-employment',5),
  ('up-secretariat-gs','indian-economy-public-finance','RBI, Banks, Credit and Monetary Policy','rbi-banks-credit',6),
  ('up-secretariat-gs','indian-economy-public-finance','Union Budget, Taxation and Fiscal Deficit','budget-taxation-fiscal-deficit',7),
  ('up-secretariat-gs','indian-economy-public-finance','Agriculture, Industry, Services and External Trade','sectors-trade-deep',8),
  ('up-secretariat-gs','general-science-technology','Motion, Heat, Light, Electricity and Everyday Physics','everyday-physics-deep',5),
  ('up-secretariat-gs','general-science-technology','Atoms, Acids, Metals and Everyday Chemistry','everyday-chemistry-deep',6),
  ('up-secretariat-gs','general-science-technology','Human Body, Nutrition, Disease and Biology','human-body-biology-deep',7),
  ('up-secretariat-gs','general-science-technology','Space, Computers, Biotechnology and New Technology','space-computers-biotech',8),
  ('up-secretariat-gs','up-history-geography-culture','Ancient, Medieval and Modern History of Uttar Pradesh','up-history-timeline',5),
  ('up-secretariat-gs','up-history-geography-culture','Freedom Movement and the 1857 Uprising in UP','up-1857-freedom-movement',6),
  ('up-secretariat-gs','up-history-geography-culture','UP Rivers, Regions, Climate and Natural Resources','up-regions-resources',7),
  ('up-secretariat-gs','up-history-geography-culture','Music, Dance, Literature, Crafts and Heritage of UP','up-heritage-arts',8),
  ('up-secretariat-gs','up-economy-administration-schemes','UP Agriculture, Crops and Food Processing','up-agriculture-food-processing',5),
  ('up-secretariat-gs','up-economy-administration-schemes','Industry, Expressways, Logistics and Infrastructure','up-infrastructure-industry',6),
  ('up-secretariat-gs','up-economy-administration-schemes','Education, Health and Social-Welfare Schemes','up-social-sector-schemes',7),
  ('up-secretariat-gs','up-economy-administration-schemes','UP Budget, Demography and Development Data','up-budget-demography-data',8),
  ('up-secretariat-gs','current-affairs-india-up-world','National Policies, Government Schemes and Institutions','national-current-affairs',5),
  ('up-secretariat-gs','current-affairs-india-up-world','UP Government Decisions, Projects and Appointments','up-current-affairs-deep',6),
  ('up-secretariat-gs','current-affairs-india-up-world','International Organisations, Summits and Agreements','international-current-affairs',7),
  ('up-secretariat-gs','current-affairs-india-up-world','Reports, Indices, Awards, Sports and Important Days','reports-awards-important-days',8),

  -- HINDI AND DRAFTING: distinguish the exact language skill being learned.
  ('up-secretariat-hindi','hindi-grammar-foundation','संधि: स्वर, व्यंजन और विसर्ग','sandhi-types',5),
  ('up-secretariat-hindi','hindi-grammar-foundation','समास: अव्ययीभाव से बहुव्रीहि','samas-types',6),
  ('up-secretariat-hindi','hindi-grammar-foundation','उपसर्ग और प्रत्यय से शब्द-निर्माण','word-formation-deep',7),
  ('up-secretariat-hindi','hindi-grammar-foundation','वर्तनी, अनुस्वार, अनुनासिक और विराम-चिह्न','spelling-punctuation-deep',8),
  ('up-secretariat-hindi','vocabulary-usage','पर्यायवाची और विलोम का प्रसंगानुसार प्रयोग','synonym-antonym-usage',5),
  ('up-secretariat-hindi','vocabulary-usage','मुहावरे और लोकोक्तियाँ: अर्थ और प्रयोग','idioms-proverbs-usage',6),
  ('up-secretariat-hindi','vocabulary-usage','अनेक शब्दों के लिए एक शब्द','one-word-substitution-deep',7),
  ('up-secretariat-hindi','vocabulary-usage','तत्सम, तद्भव और शब्द-युग्म','word-origin-pairs',8),
  ('up-secretariat-hindi','comprehension-summary','गद्यांश का विषय, उद्देश्य और मुख्य विचार','passage-main-idea-deep',5),
  ('up-secretariat-hindi','comprehension-summary','तथ्य, अनुमान, निष्कर्ष और लेखक का भाव','passage-inference-tone',6),
  ('up-secretariat-hindi','comprehension-summary','शीर्षक चयन और उपयुक्त सार','title-summary-choice',7),
  ('up-secretariat-hindi','comprehension-summary','गद्यांश में संदर्भानुसार शब्दार्थ','contextual-vocabulary',8),
  ('up-secretariat-hindi','sentence-correction-editing','लिंग, वचन और कारक की त्रुटियाँ','agreement-errors-deep',5),
  ('up-secretariat-hindi','sentence-correction-editing','काल, वाच्य और क्रिया की त्रुटियाँ','tense-voice-errors-deep',6),
  ('up-secretariat-hindi','sentence-correction-editing','वाक्य-क्रम, पद-क्रम और अन्वय','sentence-order-syntax',7),
  ('up-secretariat-hindi','sentence-correction-editing','अशुद्ध वाक्य का चरणबद्ध सुधार','sentence-correction-method',8),
  ('up-secretariat-hindi','precise-writing','सरकारी लेखन का उद्देश्य और पाठक','official-writing-purpose',5),
  ('up-secretariat-hindi','precise-writing','वाक्य को संक्षिप्त, स्पष्ट और निष्पक्ष बनाना','clear-concise-writing',6),
  ('up-secretariat-hindi','precise-writing','टिप्पणी, ज्ञापन और कार्यालयी नोट','official-note-memo',7),
  ('up-secretariat-hindi','precise-writing','मसौदा, पत्र और आदेश की संरचना','draft-letter-order',8),
  ('up-secretariat-hindi','varna-vichar-shabd-rachna-vartani','स्वर, व्यंजन और उच्चारण-स्थान','swar-vyanjan-uchcharan',5),
  ('up-secretariat-hindi','varna-vichar-shabd-rachna-vartani','शब्द-रचना और धातु आधारित शब्द','shabd-rachna-dhatu',6),
  ('up-secretariat-hindi','varna-vichar-shabd-rachna-vartani','संधि-विच्छेद के नियम और अभ्यास','sandhi-vicched-rules',7),
  ('up-secretariat-hindi','varna-vichar-shabd-rachna-vartani','समास-विग्रह के नियम और अभ्यास','samas-vigrah-rules',8),
  ('up-secretariat-hindi','parts-of-speech','संज्ञा, सर्वनाम और उनके भेद','noun-pronoun-types',5),
  ('up-secretariat-hindi','parts-of-speech','विशेषण, क्रिया और क्रिया-विशेषण','adjective-verb-adverb',6),
  ('up-secretariat-hindi','parts-of-speech','अव्यय, संबंधबोधक और समुच्चयबोधक','indeclinables-connectors',7),
  ('up-secretariat-hindi','parts-of-speech','पद-परिचय: पहचानने की विधि','part-of-speech-method',8),
  ('up-secretariat-hindi','tense-voice-case-sentence','कारक, विभक्ति और संबंध','case-markers-relations',5),
  ('up-secretariat-hindi','tense-voice-case-sentence','काल के भेद और क्रिया-रूप','tense-forms-deep',6),
  ('up-secretariat-hindi','tense-voice-case-sentence','कर्तृवाच्य, कर्मवाच्य और भाववाच्य','voice-types-deep',7),
  ('up-secretariat-hindi','tense-voice-case-sentence','वाक्य-रूपांतरण और वाक्य-भेद','sentence-transformation',8),
  ('up-secretariat-hindi','synonyms-antonyms-word-types','पर्यायवाची शब्दों का सूक्ष्म अंतर','synonym-nuance',5),
  ('up-secretariat-hindi','synonyms-antonyms-word-types','विलोम शब्द और उपसर्ग आधारित विलोम','antonym-method',6),
  ('up-secretariat-hindi','synonyms-antonyms-word-types','श्रुतिसम भिन्नार्थक शब्द','homophones-hindi',7),
  ('up-secretariat-hindi','synonyms-antonyms-word-types','शब्द-युग्म, भ्रमित शब्द और सही प्रयोग','confusing-word-pairs',8),
  ('up-secretariat-hindi','tatsam-tadbhav-deshaj-videshi','तत्सम और तद्भव पहचानने की विधि','tatsam-tadbhav-method',5),
  ('up-secretariat-hindi','tatsam-tadbhav-deshaj-videshi','देशज, विदेशी और संकर शब्द','deshaj-videshi-deep',6),
  ('up-secretariat-hindi','tatsam-tadbhav-deshaj-videshi','अनेक शब्दों के लिए एक शब्द: वर्गीकरण','one-word-categories',7),
  ('up-secretariat-hindi','tatsam-tadbhav-deshaj-videshi','संदर्भ में उपयुक्त शब्द-चयन','contextual-word-choice',8),
  ('up-secretariat-hindi','idioms-proverbs-one-word','मुहावरों का अर्थ और वाक्य-प्रयोग','muhavara-meaning-usage',5),
  ('up-secretariat-hindi','idioms-proverbs-one-word','लोकोक्तियों का भाव और प्रयोग','lokokti-meaning-usage',6),
  ('up-secretariat-hindi','idioms-proverbs-one-word','वाक्यांश के लिए एक शब्द: सामान्य श्रेणियाँ','phrase-one-word-categories',7),
  ('up-secretariat-hindi','idioms-proverbs-one-word','मिश्रित शब्द-ज्ञान अभ्यास','mixed-vocabulary-practice',8),
  ('up-secretariat-hindi','unseen-passage-comprehension','गद्यांश की संरचना और अनुच्छेद का काम','passage-structure',5),
  ('up-secretariat-hindi','unseen-passage-comprehension','मुख्य विचार और सहायक विचार','main-supporting-ideas',6),
  ('up-secretariat-hindi','unseen-passage-comprehension','तथ्य, मत और निहितार्थ','fact-opinion-implication',7),
  ('up-secretariat-hindi','unseen-passage-comprehension','समयबद्ध गद्यांश हल करने की रणनीति','timed-comprehension-strategy',8),
  ('up-secretariat-hindi','precis-title-summary','संक्षेपण में मूल भाव बचाना','precis-core-idea',5),
  ('up-secretariat-hindi','precis-title-summary','अनावश्यक विवरण हटाना','precis-remove-detail',6),
  ('up-secretariat-hindi','precis-title-summary','शीर्षक: विषय और भाव का संतुलन','precis-title-method',7),
  ('up-secretariat-hindi','precis-title-summary','सार-लेखन और शब्द-सीमा','summary-word-limit',8),
  ('up-secretariat-hindi','official-letter-note-drafting','पत्र के भाग और औपचारिक संबोधन','letter-parts-salutation',5),
  ('up-secretariat-hindi','official-letter-note-drafting','टिप्पणी, ज्ञापन और परिपत्र का अंतर','official-document-differences',6),
  ('up-secretariat-hindi','official-letter-note-drafting','प्रस्ताव, संस्तुति और आदेश-भाषा','proposal-recommendation-order',7),
  ('up-secretariat-hindi','official-letter-note-drafting','मसौदा लिखने का क्रम और जाँच-सूची','drafting-checklist',8),
  ('up-secretariat-hindi','hindi-editing-error-correction','वर्तनी और विराम-चिह्न की आम गलतियाँ','editing-spelling-punctuation',5),
  ('up-secretariat-hindi','hindi-editing-error-correction','संज्ञा-सर्वनाम और लिंग-वचन त्रुटियाँ','editing-agreement-errors',6),
  ('up-secretariat-hindi','hindi-editing-error-correction','क्रिया, काल और वाच्य त्रुटियाँ','editing-verb-tense-errors',7),
  ('up-secretariat-hindi','hindi-editing-error-correction','पूर्ण वाक्य संपादन की जाँच-सूची','full-sentence-editing',8),

  -- COMPUTER AND OFFICE SKILLS.
  ('up-secretariat-computer','computer-fundamentals','Computer Types, Generations and Uses','computer-types-generations',5),
  ('up-secretariat-computer','computer-fundamentals','CPU, ALU, Control Unit and Motherboard','cpu-alu-motherboard',6),
  ('up-secretariat-computer','computer-fundamentals','Input Devices and Output Devices','input-output-devices-deep',7),
  ('up-secretariat-computer','computer-fundamentals','Memory, Storage and Common Units','memory-storage-units',8),
  ('up-secretariat-computer','operating-systems-files','Booting, Desktop and Operating-System Roles','booting-os-basics',5),
  ('up-secretariat-computer','operating-systems-files','Files, Folders, Extensions and Paths','files-folders-paths',6),
  ('up-secretariat-computer','operating-systems-files','Compression, Backup, Recovery and Utilities','backup-recovery-utilities',7),
  ('up-secretariat-computer','operating-systems-files','Keyboard Shortcuts and File Management','file-management-shortcuts',8),
  ('up-secretariat-computer','internet-cyber-awareness','Internet, Web, Browser and Search Basics','internet-web-browser',5),
  ('up-secretariat-computer','internet-cyber-awareness','E-mail, Attachments, CC, BCC and Protocols','email-protocols',6),
  ('up-secretariat-computer','internet-cyber-awareness','Networks, Cloud Services and Collaboration','networks-cloud-collaboration',7),
  ('up-secretariat-computer','internet-cyber-awareness','Phishing, Malware, Passwords and Privacy','cyber-safety-deep',8),
  ('up-secretariat-computer','office-productivity-tools','MS Word: Text, Paragraph and Page Formatting','word-formatting-deep',5),
  ('up-secretariat-computer','office-productivity-tools','MS Word: Tables, Headers, Mail Merge and Print','word-tables-mail-merge',6),
  ('up-secretariat-computer','office-productivity-tools','MS Excel: Cells, References, Formulas and Functions','excel-formulas-functions',7),
  ('up-secretariat-computer','office-productivity-tools','MS Excel and PowerPoint: Charts, Slides and Export','office-charts-presentations',8),
  ('up-secretariat-computer','keyboard-data-entry-concepts','Keyboard Layout, Home Row and Common Keys','keyboard-layout-keys',5),
  ('up-secretariat-computer','keyboard-data-entry-concepts','Typing Accuracy, Speed and Error Correction','typing-accuracy-speed',6),
  ('up-secretariat-computer','keyboard-data-entry-concepts','Editing Commands: Select, Copy, Paste, Find and Replace','editing-commands-deep',7),
  ('up-secretariat-computer','keyboard-data-entry-concepts','Data Entry Workflow and Verification','data-entry-verification',8),
  ('up-secretariat-computer','computer-generations-system-architecture','First to Fifth Generation Computers','computer-generations-deep',5),
  ('up-secretariat-computer','computer-generations-system-architecture','Processor, Registers, ALU and Control Unit','processor-registers-alu',6),
  ('up-secretariat-computer','computer-generations-system-architecture','Motherboard, Ports and Expansion Devices','motherboard-ports-devices',7),
  ('up-secretariat-computer','computer-generations-system-architecture','Input-Process-Output-Storage Cycle','ipos-cycle',8),
  ('up-secretariat-computer','data-representation-number-systems','Bits, Bytes, KB, MB, GB and TB','storage-units-deep',5),
  ('up-secretariat-computer','data-representation-number-systems','Binary, Decimal, Octal and Hexadecimal','number-systems-deep',6),
  ('up-secretariat-computer','data-representation-number-systems','Character Codes: ASCII and Unicode','ascii-unicode',7),
  ('up-secretariat-computer','data-representation-number-systems','Boolean Logic and Data Types','boolean-logic-data-types',8),
  ('up-secretariat-computer','operating-systems-files-utilities','Operating Systems and User Interfaces','operating-systems-ui',5),
  ('up-secretariat-computer','operating-systems-files-utilities','Booting, BIOS and Device Drivers','booting-bios-drivers',6),
  ('up-secretariat-computer','operating-systems-files-utilities','File Systems, Folders and Extensions','file-systems-extensions',7),
  ('up-secretariat-computer','operating-systems-files-utilities','Backup, Restore, Antivirus and Utilities','backup-antivirus-utilities',8),
  ('up-secretariat-computer','networks-internet-email','LAN, MAN, WAN and Network Topologies','network-types-topologies',5),
  ('up-secretariat-computer','networks-internet-email','Modem, Router, Switch and Network Devices','network-devices-deep',6),
  ('up-secretariat-computer','networks-internet-email','URLs, Domains, Browsers and Search Engines','urls-domains-search',7),
  ('up-secretariat-computer','networks-internet-email','E-mail Fields, Protocols and Netiquette','email-fields-netiquette',8),
  ('up-secretariat-computer','ms-word-documents-formatting','Word Interface, Files and Templates','word-interface-templates',5),
  ('up-secretariat-computer','ms-word-documents-formatting','Fonts, Paragraphs, Styles and Page Layout','word-styles-page-layout',6),
  ('up-secretariat-computer','ms-word-documents-formatting','Tables, Lists, Headers and Footers','word-tables-headers',7),
  ('up-secretariat-computer','ms-word-documents-formatting','Mail Merge, Review, Print and PDF','word-mail-merge-pdf',8),
  ('up-secretariat-computer','ms-excel-formulas-tables-charts','Workbook, Worksheet, Cell and Reference Types','excel-references-deep',5),
  ('up-secretariat-computer','ms-excel-formulas-tables-charts','Arithmetic, Logical and Statistical Functions','excel-functions-deep',6),
  ('up-secretariat-computer','ms-excel-formulas-tables-charts','Sort, Filter, Table and Conditional Formatting','excel-data-tools',7),
  ('up-secretariat-computer','ms-excel-formulas-tables-charts','Charts, Printing and Spreadsheet Error Checks','excel-charts-printing',8),
  ('up-secretariat-computer','ms-powerpoint-presentations','Slides, Themes, Layouts and Slide Master','ppt-themes-layouts',5),
  ('up-secretariat-computer','ms-powerpoint-presentations','Text, Images, Shapes, SmartArt and Tables','ppt-content-elements',6),
  ('up-secretariat-computer','ms-powerpoint-presentations','Transitions, Animations and Timing','ppt-motion-timing',7),
  ('up-secretariat-computer','ms-powerpoint-presentations','Slide Show, Presenter View, Print and Export','ppt-show-export',8),
  ('up-secretariat-computer','databases-data-management','Database, Table, Record, Field and Data Types','database-basics-deep',5),
  ('up-secretariat-computer','databases-data-management','Primary Key, Foreign Key and Relationships','database-keys-relations',6),
  ('up-secretariat-computer','databases-data-management','Queries, Forms, Reports and Sorting','database-queries-reports',7),
  ('up-secretariat-computer','databases-data-management','Validation, Integrity and Data Backup','database-validation-backup',8),
  ('up-secretariat-computer','cyber-security-digital-safety','Virus, Worm, Trojan, Ransomware and Antivirus','malware-types-antivirus',5),
  ('up-secretariat-computer','cyber-security-digital-safety','Passwords, MFA and Authentication','passwords-mfa-auth',6),
  ('up-secretariat-computer','cyber-security-digital-safety','Phishing, Social Engineering and Safe Browsing','phishing-social-engineering',7),
  ('up-secretariat-computer','cyber-security-digital-safety','Privacy, Digital Footprint and Backups','privacy-footprint-backups',8),
  ('up-secretariat-computer','office-shortcuts-practical-commands','Windows, File Explorer and Common Commands','windows-explorer-commands',5),
  ('up-secretariat-computer','office-shortcuts-practical-commands','Word, Excel and PowerPoint Shortcuts','office-shortcuts-deep',6),
  ('up-secretariat-computer','office-shortcuts-practical-commands','Browser and E-mail Productivity Commands','browser-email-shortcuts',7),
  ('up-secretariat-computer','office-shortcuts-practical-commands','Practical Office Workflow Scenarios','office-workflow-deep',8),

  -- REASONING AND APTITUDE: a focused method for each question family.
  ('up-secretariat-reasoning','analogy-classification-series','Number and Letter Analogy','number-letter-analogy-deep',5),
  ('up-secretariat-reasoning','analogy-classification-series','Word, Figure and Symbol Classification','classification-deep',6),
  ('up-secretariat-reasoning','analogy-classification-series','Number Series and Missing Term','number-series-deep',7),
  ('up-secretariat-reasoning','analogy-classification-series','Alphabet Series and Position Logic','alphabet-series-deep',8),
  ('up-secretariat-reasoning','statements-conclusions','Statement Scope and Exact Wording','statement-scope-deep',5),
  ('up-secretariat-reasoning','statements-conclusions','Assumption, Argument and Inference','assumption-argument-inference',6),
  ('up-secretariat-reasoning','statements-conclusions','Cause, Effect and Course of Action','cause-effect-course-action',7),
  ('up-secretariat-reasoning','statements-conclusions','Conclusion Check and Option Elimination','conclusion-elimination',8),
  ('up-secretariat-reasoning','directions-relations-order','Direction Sense with Coordinate Sketch','direction-coordinate-sketch',5),
  ('up-secretariat-reasoning','directions-relations-order','Blood Relations with Family Tree','blood-relations-family-tree',6),
  ('up-secretariat-reasoning','directions-relations-order','Ranking from Both Ends','ranking-both-ends-deep',7),
  ('up-secretariat-reasoning','directions-relations-order','Order, Sequence and Relative Position','order-sequence-position',8),
  ('up-secretariat-reasoning','data-interpretation-basics','Tables: Read Before Calculating','table-reading-deep',5),
  ('up-secretariat-reasoning','data-interpretation-basics','Bar Graphs and Line Graphs','bar-line-graphs',6),
  ('up-secretariat-reasoning','data-interpretation-basics','Pie Charts, Ratios and Percentage Change','pie-ratio-percentage',7),
  ('up-secretariat-reasoning','data-interpretation-basics','Approximation, Comparison and Time Control','di-approximation-time',8),
  ('up-secretariat-reasoning','condition-first-problem-solving','Extract Conditions and Make a Constraint List','constraint-list-method',5),
  ('up-secretariat-reasoning','condition-first-problem-solving','Create a Table, Line or Grid','table-line-grid-method',6),
  ('up-secretariat-reasoning','condition-first-problem-solving','Test Cases and Eliminate Contradictions','test-cases-contradictions',7),
  ('up-secretariat-reasoning','condition-first-problem-solving','Final Option Verification Under Time','final-option-verification',8),
  ('up-secretariat-reasoning','coding-decoding-alphabet-logic','Letter and Number Coding Rules','letter-number-coding-deep',5),
  ('up-secretariat-reasoning','coding-decoding-alphabet-logic','Word, Symbol and Substitution Coding','word-symbol-coding-deep',6),
  ('up-secretariat-reasoning','coding-decoding-alphabet-logic','Alphabet Positions, Pairs and Series','alphabet-positions-pairs',7),
  ('up-secretariat-reasoning','coding-decoding-alphabet-logic','Pattern Recognition and Rule Verification','pattern-verification',8),
  ('up-secretariat-reasoning','syllogism-venn-set-logic','All, Some, None and Possibility Statements','syllogism-quantifiers',5),
  ('up-secretariat-reasoning','syllogism-venn-set-logic','Venn Diagram Construction','venn-construction',6),
  ('up-secretariat-reasoning','syllogism-venn-set-logic','Either-Or and Complementary Conclusions','either-or-conclusions',7),
  ('up-secretariat-reasoning','syllogism-venn-set-logic','Syllogism Option Elimination','syllogism-elimination',8),
  ('up-secretariat-reasoning','seating-arrangement-puzzles','Linear Seating Arrangement','linear-arrangement-deep',5),
  ('up-secretariat-reasoning','seating-arrangement-puzzles','Circular Seating Arrangement','circular-arrangement-deep',6),
  ('up-secretariat-reasoning','seating-arrangement-puzzles','Floor, Box and Scheduling Puzzles','floor-box-scheduling',7),
  ('up-secretariat-reasoning','seating-arrangement-puzzles','Condition Grid and Final Check','condition-grid-final-check',8),
  ('up-secretariat-reasoning','calendar-clock-time-logic','Odd Days, Leap Years and Day Calculation','odd-days-leap-years',5),
  ('up-secretariat-reasoning','calendar-clock-time-logic','Calendar Patterns and Date Intervals','calendar-patterns-deep',6),
  ('up-secretariat-reasoning','calendar-clock-time-logic','Clock Angles, Gains and Losses','clock-angles-gains-losses',7),
  ('up-secretariat-reasoning','calendar-clock-time-logic','Time Sequence and Scheduling Logic','time-sequence-scheduling',8),
  ('up-secretariat-reasoning','mathematical-operations-missing-values','Operator Interchange and Substitution','operator-interchange',5),
  ('up-secretariat-reasoning','mathematical-operations-missing-values','Missing Number Rows and Columns','missing-number-grid',6),
  ('up-secretariat-reasoning','mathematical-operations-missing-values','Equation Balance and Rule Discovery','equation-balance-rule',7),
  ('up-secretariat-reasoning','mathematical-operations-missing-values','Check the Rule Before Calculating','rule-before-calculation-deep',8),
  ('up-secretariat-reasoning','decision-making-statement-logic','Statement and Assumption','statement-assumption-deep',5),
  ('up-secretariat-reasoning','decision-making-statement-logic','Statement and Argument','statement-argument-deep',6),
  ('up-secretariat-reasoning','decision-making-statement-logic','Cause and Effect','cause-effect-deep',7),
  ('up-secretariat-reasoning','decision-making-statement-logic','Course of Action and Decision Choice','course-action-decision',8),
  ('up-secretariat-reasoning','non-verbal-reasoning','Figure Analogy and Classification','figure-analogy-classification-deep',5),
  ('up-secretariat-reasoning','non-verbal-reasoning','Mirror Image and Water Image','mirror-water-image-deep',6),
  ('up-secretariat-reasoning','non-verbal-reasoning','Paper Folding, Cutting and Hole Punching','paper-folding-cutting-deep',7),
  ('up-secretariat-reasoning','non-verbal-reasoning','Embedded Figures, Completion and Cube Logic','embedded-figures-cube-logic',8),
  ('up-secretariat-reasoning','data-sufficiency-data-interpretation','Data Sufficiency: Decide, Do Not Solve','data-sufficiency-method',5),
  ('up-secretariat-reasoning','data-sufficiency-data-interpretation','Tables and Bar Graph Data','tables-bar-graphs-deep',6),
  ('up-secretariat-reasoning','data-sufficiency-data-interpretation','Pie Charts, Line Graphs and Comparison','pie-line-comparison',7),
  ('up-secretariat-reasoning','data-sufficiency-data-interpretation','Estimation, Ratios and Data Checks','estimation-ratio-checks',8),
  ('up-secretariat-reasoning','order-ranking-comparison','Rank from Left, Right and Both Ends','rank-left-right-deep',5),
  ('up-secretariat-reasoning','order-ranking-comparison','Age, Height, Weight and Comparison Tables','comparison-table-method',6),
  ('up-secretariat-reasoning','order-ranking-comparison','Order of Events and Sequence Questions','event-sequence-questions',7),
  ('up-secretariat-reasoning','order-ranking-comparison','Relative Position and Arrangement Verification','relative-position-verification',8),
  ('up-secretariat-reasoning','mixed-reasoning-practice','Identify the Question Family First','identify-question-family',5),
  ('up-secretariat-reasoning','mixed-reasoning-practice','Read Conditions Before Looking at Options','conditions-before-options-deep',6),
  ('up-secretariat-reasoning','mixed-reasoning-practice','Use Elimination Without Guessing','elimination-without-guessing',7),
  ('up-secretariat-reasoning','mixed-reasoning-practice','Timed Mixed Sets and Error Review','timed-mixed-error-review',8)
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, r.name, r.slug,
       format('Learn %s as a focused Samiksha Adhikari preparation unit, then practise and revisit it.', r.name),
       r.ord
from raw r
join public.chapters c on c.subject_id = r.subject_id and c.slug = r.chapter_slug
on conflict (chapter_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  order_index = excluded.order_index;
