-- Editorial backfill batch: 31 August 2026.
-- Each brief is based on a primary PIB release and rewritten for exam preparation.

insert into public.current_affairs_briefs (
  slug, published_on, title, summary, why_it_matters, background,
  source_title, source_url, source_publisher, source_published_on,
  prelims_takeaways, quick_check, visual_data, status, reviewed_at
) values
(
  '2026-08-31-sone-river-water-sharing-mou',
  '2026-08-31',
  'Bihar and Jharkhand sign an MoU on Sone River water sharing',
  'Bihar and Jharkhand signed a memorandum of understanding on sharing Sone River water in the presence of Union and state representatives. The release linked the arrangement with irrigation and drinking-water needs in the two states.',
  'River-water disputes are a recurring federalism theme. This update is useful for distinguishing an inter-state arrangement from the constitutional and institutional mechanisms that may be used when water conflicts persist.',
  'Water is a State List subject, but inter-state rivers can create disputes that require coordination across state boundaries. An MoU records an agreed framework between parties; it is different from a court judgment or a law enacted by Parliament.',
  'PIB: Bihar and Jharkhand MoU on sharing Sone River water',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2305138&lang=1&reg=48',
  'Press Information Bureau',
  '2026-08-31',
  '["An MoU records an agreed arrangement between the parties.", "Inter-state river questions connect water governance with cooperative federalism.", "Irrigation and drinking water are common policy objectives in river-water arrangements.", "An agreement, a tribunal award and a court judgment are distinct legal or institutional outcomes."]'::jsonb,
  '[{"question":"What does an MoU generally record?","answer":"A mutually agreed framework or understanding between the parties."},{"question":"Why can a river become an inter-state governance issue?","answer":"A river basin can cross state boundaries, so the use of its water can affect more than one state."}]'::jsonb,
  '{"title":"Read a river-water update in four steps","steps":["Identify the river and the states concerned.","Separate the immediate arrangement from the wider constitutional context.","Note the stated uses: irrigation, drinking water, hydropower or ecology.","Ask whether the development is an MoU, a tribunal process, a judgment or legislation."]}'::jsonb,
  'published', now()
),
(
  '2026-08-31-union-government-accounts-july-2026',
  '2026-08-31',
  'Union Government accounts till July: how to read receipts, expenditure and fiscal progress',
  'The Ministry of Finance released the consolidated monthly accounts of the Union Government up to July 2026. The release reported total receipts, expenditure, revenue and capital components, and the tax devolution transferred to states.',
  'Budget questions often test classification rather than headline numbers. This item is a prompt to practise the differences between revenue and capital accounts, tax and non-tax revenue, and the Centre''s tax devolution to states.',
  'Government accounts classify receipts and expenditure by their nature. Revenue expenditure does not normally create assets, while capital expenditure can create assets or reduce liabilities. Tax devolution is the share of divisible taxes transferred to states under the constitutional finance framework.',
  'PIB: Monthly Review of Accounts of Union Government up to July 2026',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2305025&lang=1&reg=3',
  'Press Information Bureau',
  '2026-08-31',
  '["Revenue and capital accounts are different budget classifications.", "Tax revenue and non-tax revenue are both parts of government receipts.", "Tax devolution transfers a share of central taxes to states.", "Monthly accounts track progress against the annual Budget Estimates."]'::jsonb,
  '[{"question":"Which type of expenditure is commonly associated with creating assets?","answer":"Capital expenditure."},{"question":"What is tax devolution?","answer":"The transfer of a share of central taxes to state governments under the constitutional finance framework."}]'::jsonb,
  '{"title":"Decode a government-account headline","steps":["Check the reporting period and financial year.","Separate receipts from expenditure.","Classify figures as revenue or capital where relevant.","Read percentages against Budget Estimates as progress, not as the final annual outcome."]}'::jsonb,
  'published', now()
),
(
  '2026-08-31-upi-uzqr-uzbekistan',
  '2026-08-31',
  'UPI payment access expands in Uzbekistan through UZQR',
  'NPCI International Payments Ltd. and Uzbekistan''s National Interbank Processing Centre agreed to enable UPI-based merchant payments through Uzbekistan''s interoperable UZQR code. The arrangement is intended to let Indian visitors use eligible UPI applications for merchant payments there.',
  'UPI''s international expansion is important for questions on digital public infrastructure, cross-border payments and India''s economic engagement. Remember the difference between UPI, its international arm, and a country''s domestic payment network.',
  'UPI is India''s instant-payment interface. NPCI International Payments Ltd. is the international arm of the National Payments Corporation of India. Interoperable QR arrangements allow payment systems to connect through common merchant-acceptance infrastructure.',
  'PIB: NPCI International and Uzbekistan''s NIPC partner to enable UPI payments via UZQR',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2304967&lang=1&reg=48',
  'Press Information Bureau',
  '2026-08-31',
  '["UPI is an instant-payment interface used in India.", "NIPL is the international arm of NPCI.", "Interoperable QR systems can support merchant payments across connected payment networks.", "Uzbekistan''s national interoperable QR code in this arrangement is UZQR."]'::jsonb,
  '[{"question":"What is the purpose of an interoperable QR arrangement?","answer":"It allows compatible payment applications and merchant QR infrastructure to work across connected payment networks."},{"question":"NIPL is associated with which Indian payment ecosystem?","answer":"The National Payments Corporation of India (NPCI) ecosystem."}]'::jsonb,
  '{"title":"From a phone scan to cross-border payment","steps":["A merchant displays an interoperable QR code.","A visitor scans it with an eligible payment application.","The connected payment networks route and validate the transaction.","The arrangement makes merchant acceptance easier without replacing every domestic payment system."]}'::jsonb,
  'published', now()
),
(
  '2026-08-31-quantum-biotechnology-national-quantum-mission',
  '2026-08-31',
  'Quantum biotechnology: linking quantum tools with life sciences',
  'A national conference on quantum biotechnology brought together researchers, clinicians, industry and start-ups to discuss applications such as diagnostics, biomedical imaging, drug discovery and precision medicine in the context of the National Quantum Mission.',
  'For science and technology preparation, the useful lesson is not to memorise a buzzword. Link the technology to a plausible use: sensing and imaging can support measurement, while computation can support complex analysis and design.',
  'Quantum technologies use effects described by quantum mechanics in fields such as computing, communication, sensing and metrology. Biotechnology applies biological knowledge and techniques to practical uses in health, agriculture and industry.',
  'PIB: National Conference on Quantum Biotechnology',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2304999&lang=2&reg=48',
  'Press Information Bureau',
  '2026-08-31',
  '["Quantum technology includes computing, communication, sensing and metrology.", "Biotechnology has applications in health, agriculture and industry.", "Biomedical imaging and diagnostics are examples of health-related technology applications.", "The National Quantum Mission is associated with India''s quantum-technology ecosystem."]'::jsonb,
  '[{"question":"Which quantum-technology area is especially relevant to precise measurement?","answer":"Quantum sensing and metrology."},{"question":"Why is quantum biotechnology interdisciplinary?","answer":"It combines quantum tools with life-science and health applications."}]'::jsonb,
  '{"title":"Turn a frontier-tech headline into an answer","steps":["Name the scientific field accurately.","Identify the tool: computing, communication, sensing or metrology.","Connect it to a concrete application such as imaging or diagnostics.","Avoid claiming that a research direction is already a universal everyday service."]}'::jsonb,
  'published', now()
),
(
  '2026-08-31-blue-economy-lakshadweep-fisheries',
  '2026-08-31',
  'Lakshadweep fisheries outreach highlights the Blue Economy',
  'A fisheries outreach programme at Agatti, Lakshadweep focused on sustainable use of island resources such as tuna, seaweed and ornamental fisheries. The release also referred to fisheries farmer producer organisations, cooperatives and Mission Rangeen Machhli 2031 for ornamental fisheries development.',
  'Blue Economy questions reward balanced answers: economic opportunity from oceans must be paired with ecological sustainability, livelihoods and conservation. Islands are especially relevant because coastal and marine ecosystems are closely connected there.',
  'The Blue Economy refers to sustainable use of ocean and coastal resources for livelihoods and economic development. Fisheries management can involve harvesting, value chains, producer organisations, cooperatives, habitat protection and resource monitoring.',
  'PIB: Fisheries outreach programme at Agatti, Lakshadweep',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2304929&lang=1&reg=3',
  'Press Information Bureau',
  '2026-08-31',
  '["The Blue Economy joins marine economic activity with sustainability.", "Lakshadweep is an Indian island territory in the Arabian Sea.", "Seaweed, tuna and ornamental fisheries are distinct marine-resource segments.", "Producer organisations and cooperatives can support value chains and livelihoods."]'::jsonb,
  '[{"question":"What makes an economic activity part of the Blue Economy?","answer":"It uses ocean or coastal resources while aiming to protect marine ecosystems and sustain livelihoods."},{"question":"Why are producer organisations relevant in fisheries?","answer":"They can improve collective access to inputs, services, markets and value addition for fishers."}]'::jsonb,
  '{"title":"A balanced Blue Economy answer","steps":["Start with the marine or coastal resource.","Add livelihood and value-chain opportunities.","State the sustainability condition: avoid degrading ecosystems or stocks.","Mention governance tools such as cooperatives, monitoring or habitat protection."]}'::jsonb,
  'published', now()
),
(
  '2026-08-31-renewable-energy-300-gw-roadshow',
  '2026-08-31',
  'Clean-energy roadshow spotlights non-fossil capacity and the 2030 target',
  'At the Bharat Renewable Energy Summit roadshow in Hyderabad, the Ministry of New and Renewable Energy said India''s installed non-fossil-fuel capacity had crossed 300 GW and linked the discussion to the country''s 500 GW non-fossil-capacity target for 2030.',
  'Energy-transition questions require precision. Installed capacity is the maximum output a system can generate under specified conditions; it is not the same as actual electricity generation over a period. Non-fossil also does not mean solar alone.',
  'Non-fossil electricity capacity can include renewable sources such as solar, wind and hydro as well as nuclear power. Capacity is measured in watts, while electricity generated over time is measured in watt-hours. The transition also requires grids, storage and transmission.',
  'PIB: Bharat Renewable Energy Summit 2026 Roadshow reaches Hyderabad',
  'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2305177&lang=2&reg=48',
  'Press Information Bureau',
  '2026-08-31',
  '["Capacity and actual generation are different measures.", "Non-fossil capacity is broader than solar capacity alone.", "India''s stated target in the release is 500 GW of non-fossil capacity by 2030.", "Grid integration, transmission and storage are central transition challenges."]'::jsonb,
  '[{"question":"Why can installed capacity and electricity generation differ?","answer":"Capacity is potential maximum output; actual generation depends on operation, availability and conditions over time."},{"question":"Is non-fossil capacity limited to solar power?","answer":"No. It can include several non-fossil sources, including renewable sources and nuclear power."}]'::jsonb,
  '{"title":"Do not confuse power with energy","steps":["Capacity answers: how much output can be produced at a moment?","Generation answers: how much electricity was produced over time?","Check whether a target refers to capacity, generation share or emissions.","Add enabling systems: grids, transmission, storage and demand management."]}'::jsonb,
  'published', now()
)
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  why_it_matters = excluded.why_it_matters,
  background = excluded.background,
  source_title = excluded.source_title,
  source_url = excluded.source_url,
  source_publisher = excluded.source_publisher,
  source_published_on = excluded.source_published_on,
  prelims_takeaways = excluded.prelims_takeaways,
  quick_check = excluded.quick_check,
  visual_data = excluded.visual_data,
  status = excluded.status,
  reviewed_at = excluded.reviewed_at,
  updated_at = now();
