-- Replaces the five-chapter placeholder map for Delhi Police Constable with
-- a fuller, navigation-ready syllabus taxonomy. The parent areas follow the
-- SSC's indicative objective-exam areas; the chapter and topic grouping is
-- ExamGrind's original learning map, not a claim that SSC publishes fixed
-- chapter counts. Review the next official notification before asserting a
-- marks split, date, or any notification-specific condition.

-- UPPSC PCS is not public until its large syllabus has the same depth.
update public.exams set status = 'coming_soon' where slug = 'uppsc-pcs';

-- Preserve any early learner evidence. Existing chapter/topic rows are
-- upgraded in place where possible, and the missing structure is appended.

with raw(subject_id, name, slug, ord) as (values
  -- General Knowledge and Current Affairs
  ('dp-gk', 'Indian Polity & Constitution', 'indian-polity', 1),
  ('dp-gk', 'Modern India & Freedom Movement', 'modern-indian-history', 2),
  ('dp-gk', 'Indian Art & Culture', 'indian-art-culture', 3),
  ('dp-gk', 'Indian Geography', 'indian-geography', 4),
  ('dp-gk', 'World Geography & Environment', 'world-geography-environment', 5),
  ('dp-gk', 'Ancient & Medieval India', 'ancient-medieval-india', 6),
  ('dp-gk', 'Governance & Public Institutions', 'governance-public-institutions', 7),
  ('dp-gk', 'Indian Economy', 'indian-economy', 8),
  ('dp-gk', 'Physics in Everyday Life', 'everyday-physics', 9),
  ('dp-gk', 'Chemistry in Everyday Life', 'everyday-chemistry', 10),
  ('dp-gk', 'Biology & Human Health', 'biology-human-health', 11),
  ('dp-gk', 'Technology, Space & Defence', 'technology-space-defence', 12),
  ('dp-gk', 'Sports, Awards & Books', 'sports-awards-books', 13),
  ('dp-gk', 'Current Affairs Revision', 'current-affairs-method', 14),
  -- Reasoning
  ('dp-reasoning', 'Analogy & Classification', 'analogy-classification', 1),
  ('dp-reasoning', 'Series & Coding-Decoding', 'series-coding', 2),
  ('dp-reasoning', 'Directions, Relations & Ranking', 'directions-relations-ranking', 3),
  ('dp-reasoning', 'Syllogism & Venn Diagrams', 'syllogism-venn', 4),
  ('dp-reasoning', 'Word Formation & Dictionary Order', 'word-formation-dictionary-order', 6),
  ('dp-reasoning', 'Directions & Distance', 'directions-distance', 7),
  ('dp-reasoning', 'Blood Relations', 'blood-relations', 8),
  ('dp-reasoning', 'Ranking, Order & Seating', 'ranking-order-seating', 9),
  ('dp-reasoning', 'Venn Diagrams & Set Relations', 'venn-set-relations', 10),
  ('dp-reasoning', 'Syllogism & Statement Logic', 'syllogism-statement-logic', 11),
  ('dp-reasoning', 'Calendar, Clock & Age', 'calendar-clock-age', 12),
  ('dp-reasoning', 'Mathematical Operations', 'mathematical-operations', 13),
  ('dp-reasoning', 'Figure Analogy & Classification', 'figure-analogy-classification', 14),
  ('dp-reasoning', 'Mirror, Water & Embedded Figures', 'mirror-water-embedded-figures', 15),
  ('dp-reasoning', 'Paper Folding, Cube & Dice', 'paper-folding-cube-dice', 16),
  -- Numerical Ability
  ('dp-quant', 'Number System & Simplification', 'number-system-simplification', 1),
  ('dp-quant', 'Percentages, Ratio & Average', 'percentages-ratio-average', 2),
  ('dp-quant', 'Profit, Loss & Interest', 'profit-loss-interest', 3),
  ('dp-quant', 'Time, Work, Speed & Distance', 'time-work-speed-distance', 4),
  ('dp-quant', 'Mensuration & Data Interpretation', 'mensuration-data-interpretation', 5),
  ('dp-quant', 'HCF, LCM, Surds & Indices', 'hcf-lcm-surds-indices', 6),
  ('dp-quant', 'Decimals, Fractions & Recurring Values', 'decimals-fractions-recurring-values', 7),
  ('dp-quant', 'Ratio, Proportion & Partnership', 'ratio-proportion-partnership', 8),
  ('dp-quant', 'Simple & Compound Interest', 'simple-compound-interest', 9),
  ('dp-quant', 'Pipes & Cisterns', 'pipes-cisterns', 10),
  ('dp-quant', 'Time, Speed & Distance', 'time-speed-distance', 12),
  ('dp-quant', 'Trains, Boats & Streams', 'trains-boats-streams', 13),
  ('dp-quant', 'Algebra', 'algebra', 14),
  ('dp-quant', 'Geometry', 'geometry', 15),
  ('dp-quant', 'Mensuration', 'mensuration', 16),
  ('dp-quant', 'Trigonometry & Heights-Distances', 'trigonometry-heights-distances', 17),
  -- Computer Awareness
  ('dp-computer', 'Computer Fundamentals', 'computer-fundamentals', 1),
  ('dp-computer', 'Hardware, Memory & Storage', 'hardware-memory-storage', 2),
  ('dp-computer', 'Operating Systems & Files', 'operating-systems-files', 3),
  ('dp-computer', 'Internet, Networks & Cyber Safety', 'internet-networks-cyber-safety', 4),
  ('dp-computer', 'Office Tools & Shortcuts', 'office-tools-shortcuts', 5),
  ('dp-computer', 'Computer Basics & Generations', 'computer-basics-generations', 6),
  ('dp-computer', 'Software & Operating Systems', 'software-operating-systems', 7),
  ('dp-computer', 'Number Systems & Data Representation', 'number-systems-data-representation', 8),
  ('dp-computer', 'Internet, Web & Email', 'internet-web-email', 9),
  ('dp-computer', 'Networks & Communication', 'networks-communication', 10),
  ('dp-computer', 'Cyber Security & Digital Safety', 'cyber-security-digital-safety', 11),
  ('dp-computer', 'MS Word', 'ms-word', 12),
  ('dp-computer', 'MS Excel', 'ms-excel', 13),
  ('dp-computer', 'MS PowerPoint & Keyboard Shortcuts', 'ms-powerpoint-keyboard-shortcuts', 14)
)
insert into public.chapters (subject_id, name, slug, order_index)
select subject_id, name, slug, ord from raw
on conflict (subject_id, slug) do update set
  name = excluded.name,
  order_index = excluded.order_index;

with raw(subject_id, chapter_slug, name, slug, ord) as (values
  ('dp-gk','ancient-medieval-india','Indus Valley Civilisation','indus-valley',1),
  ('dp-gk','ancient-medieval-india','Vedic Age, Buddhism & Jainism','vedic-buddhism-jainism',2),
  ('dp-gk','ancient-medieval-india','Maurya, Gupta & Regional Kingdoms','maurya-gupta-regional-kingdoms',3),
  ('dp-gk','ancient-medieval-india','Delhi Sultanate & Mughal India','sultanate-mughal-india',4),
  ('dp-gk','modern-india-freedom-movement','Company Rule & British Expansion','company-rule-british-expansion',1),
  ('dp-gk','modern-india-freedom-movement','Reform Movements & Revolt of 1857','reform-movements-1857',2),
  ('dp-gk','modern-india-freedom-movement','National Movement & Gandhian Phase','national-movement-gandhian-phase',3),
  ('dp-gk','modern-india-freedom-movement','Acts, Sessions & Important Leaders','acts-sessions-leaders',4),
  ('dp-gk','indian-art-culture','Architecture, Painting & Dance','architecture-painting-dance',1),
  ('dp-gk','indian-art-culture','Music, Literature & Festivals','music-literature-festivals',2),
  ('dp-gk','indian-geography','Physiography, Rivers & Climate','physiography-rivers-climate',1),
  ('dp-gk','indian-geography','Soils, Agriculture & Minerals','soils-agriculture-minerals',2),
  ('dp-gk','indian-geography','States, Neighbours & Mapping','states-neighbours-mapping',3),
  ('dp-gk','world-geography-environment','Earth, Atmosphere & Ocean Basics','earth-atmosphere-oceans',1),
  ('dp-gk','world-geography-environment','Ecology, Biodiversity & Pollution','ecology-biodiversity-pollution',2),
  ('dp-gk','indian-polity','Preamble, Rights & Duties','preamble-rights-duties',1),
  ('dp-gk','indian-polity','President, Parliament & Judiciary','president-parliament-judiciary',2),
  ('dp-gk','indian-polity','Centre-State & Constitutional Bodies','centre-state-constitutional-bodies',3),
  ('dp-gk','governance-public-institutions','Local Government & Public Services','local-government-public-services',1),
  ('dp-gk','governance-public-institutions','Major Schemes, Reports & Indices','schemes-reports-indices',2),
  ('dp-gk','indian-economy','National Income, Inflation & Banking','national-income-inflation-banking',1),
  ('dp-gk','indian-economy','Budget, Taxation & External Sector','budget-taxation-external-sector',2),
  ('dp-gk','everyday-physics','Motion, Force, Work & Energy','motion-force-work-energy',1),
  ('dp-gk','everyday-physics','Heat, Light, Sound & Electricity','heat-light-sound-electricity',2),
  ('dp-gk','everyday-chemistry','Matter, Acids, Bases & Salts','matter-acids-bases-salts',1),
  ('dp-gk','everyday-chemistry','Metals, Non-metals & Daily Chemistry','metals-nonmetals-daily-chemistry',2),
  ('dp-gk','biology-human-health','Cell, Plant & Animal Basics','cell-plant-animal-basics',1),
  ('dp-gk','biology-human-health','Human Systems, Disease & Nutrition','human-systems-disease-nutrition',2),
  ('dp-gk','technology-space-defence','Space, Defence & Digital Technology','space-defence-digital-technology',1),
  ('dp-gk','sports-awards-books','Awards, Sports & Important Books','awards-sports-books',1),
  ('dp-gk','current-affairs-method','Appointments, Summits & Organisations','appointments-summits-organisations',1),
  ('dp-gk','current-affairs-method','Monthly Issue Review','monthly-issue-review',2),
  ('dp-reasoning','analogy-classification','Word & Meaning Analogy','word-meaning-analogy',1),
  ('dp-reasoning','analogy-classification','Number, Symbol & Figure Classification','number-symbol-figure-classification',2),
  ('dp-reasoning','series-coding','Number & Alphabet Series','number-alphabet-series-topic',1),
  ('dp-reasoning','series-coding','Letter, Number & Pattern Coding','letter-number-pattern-coding',2),
  ('dp-reasoning','word-formation-dictionary-order','Word Formation & Dictionary Order','word-formation-dictionary-order-topic',1),
  ('dp-reasoning','directions-relations-ranking','Turns, Distance & Final Direction','turns-distance-final-direction',1),
  ('dp-reasoning','directions-relations-ranking','Family Tree & Coded Relations','family-tree-coded-relations',2),
  ('dp-reasoning','directions-relations-ranking','Rank, Position & Linear Arrangement','rank-position-linear-arrangement',3),
  ('dp-reasoning','syllogism-venn','Venn Diagrams & Group Overlap','venn-diagrams-group-overlap',1),
  ('dp-reasoning','syllogism-venn','Syllogism & Possibility','syllogism-possibility',2),
  ('dp-reasoning','syllogism-venn','Statement, Assumption & Conclusion','statement-assumption-conclusion',3),
  ('dp-reasoning','calendar-clock-age','Calendar, Clock & Age Problems','calendar-clock-age-problems',1),
  ('dp-reasoning','mathematical-operations','Operator Substitution & Equation Balance','operator-substitution-equation-balance',1),
  ('dp-reasoning','non-verbal-reasoning','Figure Analogy, Classification & Completion','figure-analogy-classification-completion',1),
  ('dp-reasoning','non-verbal-reasoning','Mirror, Water & Embedded Figures','mirror-water-embedded-figures-topic',2),
  ('dp-reasoning','non-verbal-reasoning','Paper Folding, Cube & Dice','paper-folding-cube-dice-topic',3),
  ('dp-quant','number-system-simplification','Divisibility, Remainders & Unit Digit','divisibility-remainders-unit-digit',1),
  ('dp-quant','number-system-simplification','Integers, Factors, Multiples & BODMAS','integers-factors-multiples-bodmas',2),
  ('dp-quant','hcf-lcm-surds-indices','HCF & LCM','hcf-lcm',1),
  ('dp-quant','hcf-lcm-surds-indices','Surds & Indices','surds-indices',2),
  ('dp-quant','decimals-fractions-recurring-values','Decimals, Fractions & Comparison','decimals-fractions-comparison',1),
  ('dp-quant','percentages-ratio-average','Percentage Base, Ratio & Proportion','percentage-base-ratio-proportion',1),
  ('dp-quant','percentages-ratio-average','Average, Mixture & Partnership','average-mixture-partnership',2),
  ('dp-quant','profit-loss-interest','Profit, Loss, Discount & Marked Price','profit-loss-discount-marked-price-topic',1),
  ('dp-quant','profit-loss-interest','Simple & Compound Interest','simple-compound-interest-topic',2),
  ('dp-quant','simple-compound-interest','Simple Interest','simple-interest',1),
  ('dp-quant','simple-compound-interest','Compound Interest','compound-interest',2),
  ('dp-quant','time-work-speed-distance','Work Efficiency, Pipes & Cisterns','work-efficiency-pipes-cisterns',1),
  ('dp-quant','time-work-speed-distance','Speed, Distance, Trains & Boats','speed-distance-trains-boats',2),
  ('dp-quant','pipes-cisterns','Pipes, Cisterns & Leakage','pipes-cisterns-leakage',1),
  ('dp-quant','algebra','Identities, Linear Equations & Simplification','identities-linear-equations',1),
  ('dp-quant','geometry','Lines, Angles & Triangles','lines-angles-triangles',1),
  ('dp-quant','geometry','Quadrilaterals & Circles','quadrilaterals-circles',2),
  ('dp-quant','mensuration','2D Mensuration','two-dimensional-mensuration',1),
  ('dp-quant','mensuration','3D Mensuration','three-dimensional-mensuration',2),
  ('dp-quant','trigonometry-heights-distances','Trigonometric Ratios & Identities','trigonometric-ratios-identities',1),
  ('dp-quant','trigonometry-heights-distances','Heights & Distances','heights-distances',2),
  ('dp-quant','mensuration-data-interpretation','2D & 3D Mensuration','two-dimensional-three-dimensional-mensuration',1),
  ('dp-quant','mensuration-data-interpretation','Tables, Bar Graphs & Pie Charts','tables-bar-graphs-pie-charts',2),
  ('dp-computer','computer-basics-generations','Computer Characteristics & Generations','computer-characteristics-generations',1),
  ('dp-computer','computer-fundamentals','CPU, Input, Output & Generations','cpu-input-output-generations',1),
  ('dp-computer','hardware-memory-storage','Primary, Secondary & Cloud Storage','primary-secondary-cloud-storage',1),
  ('dp-computer','operating-systems-files','System, Application & Utility Software','system-application-utility-software',1),
  ('dp-computer','operating-systems-files','Operating System, Files & Extensions','operating-system-files-extensions',2),
  ('dp-computer','number-systems-data-representation','Binary, Decimal & Data Units','binary-decimal-data-units',1),
  ('dp-computer','internet-networks-cyber-safety','Internet, Browser, Email & Networks','internet-browser-email-networks',1),
  ('dp-computer','internet-networks-cyber-safety','Malware, Phishing & Safe Practice','malware-phishing-safe-practice',2),
  ('dp-computer','office-tools-shortcuts','Word, Excel & Presentation Basics','word-excel-presentation-basics',1),
  ('dp-computer','office-tools-shortcuts','Common Keyboard Shortcuts','common-keyboard-shortcuts',2),
  ('dp-computer','software-operating-systems','System, Application & Utility Software','system-application-utility-software-topic',1),
  ('dp-computer','internet-web-email','Internet, Browser & Search','internet-browser-search',1),
  ('dp-computer','internet-web-email','Email, URL & Protocol Basics','email-url-protocol-basics',2),
  ('dp-computer','networks-communication','Network Types & Topologies','network-types-topologies',1),
  ('dp-computer','cyber-security-digital-safety','Malware, Phishing & Safe Practice','malware-phishing-safe-practice-topic',1),
  ('dp-computer','ms-word','Formatting, Tables & Mail Merge','formatting-tables-mail-merge',1),
  ('dp-computer','ms-excel','Cells, Formulas & Functions','cells-formulas-functions',1),
  ('dp-computer','ms-excel','Charts, Sorting & Filtering','charts-sorting-filtering',2),
  ('dp-computer','ms-powerpoint-keyboard-shortcuts','Slides, Views & Presentation Basics','slides-views-presentation-basics',1),
  ('dp-computer','ms-powerpoint-keyboard-shortcuts','Common Keyboard Shortcuts','common-keyboard-shortcuts-topic',2)
)
insert into public.topics (chapter_id, name, slug, description, order_index)
select c.id, r.name, r.slug,
  format('Build %s for Delhi Police Constable objective practice.', r.name), r.ord
from raw r
join public.chapters c on c.subject_id = r.subject_id and c.slug = r.chapter_slug
on conflict (chapter_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  order_index = excluded.order_index;
