import type { Metadata } from "next";
import LegalPageLayout from "@/components/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms of Service — ExamGrind",
  description: "Terms governing your use of ExamGrind.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="Last updated: 16 May 2026">
      <p>
        Welcome to ExamGrind (the &ldquo;Service&rdquo;). These Terms of Service
        (&ldquo;Terms&rdquo;) govern your access to and use of the ExamGrind
        website, mobile interfaces, and related services operated by{" "}
        <strong>[Your Registered Business Name]</strong>{" "}
        (&ldquo;ExamGrind&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;).
      </p>
      <p>
        By signing in or using any part of the Service, you agree to be bound by
        these Terms. If you do not agree, please do not use the Service.
      </p>

      <h2>1. Who can use ExamGrind</h2>
      <p>
        ExamGrind is a learning platform for aspirants of competitive exams in
        India, currently CUET UG (Common University Entrance Test), SSC CGL
        (Staff Selection Commission Combined Graduate Level), and NEET UG
        (National Eligibility cum Entrance Test, Undergraduate). You may use
        the Service if you are at least 13 years old. If you are under 18, you
        must have a parent or legal guardian&apos;s consent.
      </p>

      <h2>2. Your account</h2>
      <p>
        You sign in using a Google account. You are responsible for any
        activity that happens on your account. Don&apos;t share your account.
        Tell us immediately if you believe your account has been accessed
        without permission.
      </p>

      <h2>3. What you get on the free tier</h2>
      <ul>
        <li>Up to 3 practice quizzes (lifetime).</li>
        <li>One (1) Deep Analysis on a completed quiz.</li>
        <li>Access to streaks, mastery progress, and chapter paths.</li>
      </ul>

      <h2>4. What you get on the paid tier (₹75 / month)</h2>
      <ul>
        <li>Unlimited quizzes across every supported exam, subject, and topic.</li>
        <li>Unlimited Deep Analyses on every quiz you complete.</li>
        <li>Unlimited Deep Dive — our most thorough AI analysis.</li>
        <li>Drill-the-concept mini-quizzes on demand.</li>
        <li>Priority on new features as we ship them.</li>
      </ul>
      <p>
        Subscriptions auto-renew monthly until cancelled. You can cancel any
        time from your account; cancellation stops future charges but does
        not refund the current cycle except as set out in our{" "}
        <a href="/refund">Refund Policy</a>.
      </p>

      <h2>5. Payments</h2>
      <p>
        Payments are processed by Razorpay, an RBI-authorised payment
        aggregator. We never store your card number, UPI ID, or bank
        credentials on our servers. Indian taxes (e.g. GST) are charged where
        applicable.
      </p>

      <h2>6. Content generated by ExamGrind</h2>
      <p>
        Quiz questions, explanations, walkthroughs, and Deep Analyses are
        generated by AI (Anthropic&apos;s Claude family) trained on a wide range
        of public material. We do our best to ensure accuracy and alignment
        with the official syllabi (NCERT for CUET / NEET UG, and the latest
        SSC CGL syllabus for SSC aspirants), but:
      </p>
      <ul>
        <li>
          AI-generated content can contain errors. Treat ExamGrind as a
          practice partner, not the official syllabus. NCERT textbooks (for
          CUET and NEET UG) and the official SSC, NTA, and respective
          conducting-body notifications remain the authoritative sources.
        </li>
        <li>
          You will not pass questions or analyses off as your own original work
          for any academic submission.
        </li>
      </ul>

      <h2>7. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Reverse-engineer, scrape, or systematically download the Service.</li>
        <li>Bypass the free-tier limits via multiple accounts or other means.</li>
        <li>Use the Service to harass, defraud, or violate the rights of others.</li>
        <li>
          Resell, sublicense, or commercialise content generated by the
          Service.
        </li>
      </ul>

      <h2>8. Intellectual property</h2>
      <p>
        The ExamGrind brand, design, code, and underlying systems are owned
        by us. You retain ownership of anything you input (e.g. your answers).
        You grant us a limited licence to use your inputs to provide and
        improve the Service.
      </p>

      <h2>9. Disclaimer</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo;. We do not guarantee that
        practising on ExamGrind will produce any specific score, rank, or
        admission outcome. Your results depend on many factors outside our
        control.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by Indian law, ExamGrind&apos;s total
        aggregate liability to you for any claim arising out of or relating
        to the Service is limited to the amount you have paid us in the 12
        months preceding the claim, or ₹1,000, whichever is greater.
      </p>

      <h2>11. Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or
        terminate accounts that violate these Terms, after notice where
        reasonable. Sections that by their nature should survive (IP,
        liability, governing law) will survive termination.
      </p>

      <h2>12. Changes to these Terms</h2>
      <p>
        We may update these Terms occasionally. We&apos;ll change the
        &ldquo;Last updated&rdquo; date at the top, and meaningful changes
        will be notified by email or in-app. Continued use after the change
        means you accept the updated Terms.
      </p>

      <h2>13. Governing law &amp; jurisdiction</h2>
      <p>
        These Terms are governed by the laws of the Republic of India. Any
        dispute will be subject to the exclusive jurisdiction of the courts
        at <strong>[Your City]</strong>, India.
      </p>

      <h2>14. Contact</h2>
      <p>
        For any questions about these Terms, please reach out via the{" "}
        <a href="/contact">contact page</a>.
      </p>
    </LegalPageLayout>
  );
}
